<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PRECONDITIONS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cb8d2129-bd72-4a9d-8f82-45f17ccd2cb6</testSuiteGuid>
   <testCaseLink>
      <guid>eace9be6-b463-4178-a592-78a8180c7470</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Add Google Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e88cd2f-680d-42db-a7e2-826ea237a368</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6f6c7d6-8082-42cd-94ef-b88d677bec67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f971bf-ed15-4eab-842d-618ca15c6575</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d53f945-b808-469c-82a0-320bec8be125</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Clear All Notifications</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60826613-18de-41a2-963f-9dee673344ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df971593-e5f0-4665-9d55-47a077e8fcf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8481892-36f2-4e4e-b808-3b6e4ff5a3d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d266872b-1148-46db-a9e8-c4e2de372cff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Delete All Albums From Gallery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4cb2126-48a1-4076-96b8-898400a4f94e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a62d006b-c948-4cd8-9153-95f813e4f010</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8130b2c0-119d-45d5-b95d-c01c0d093194</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6fa389b-2a63-4142-b69e-1dfec733f15a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Delete Camera Photo and Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>625ec993-e678-4cf6-9b28-0fe0b18268f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53609230-2059-4d64-89fb-a141f771e313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85ad456-af28-40a3-965a-3b39eb965d02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dade7907-7586-4a9d-b2e1-cd1b5f4cb671</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Delete Emergency contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75818a86-517d-4b66-a245-6620fe48d4f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cea1f45-a3ca-45b1-bad2-36870282e824</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69161949-0c8e-4b37-afe4-910dba502864</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d03f2fe-857d-4487-8c91-d4ac9226608d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Delete Emergency information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac6720a-58f8-45d2-a5e8-32ae15c9567b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c4dd774-050c-4b38-a4a2-3c034660a269</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08a644e-13dc-43e0-a09a-01fefcff9de4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96cb8478-9e05-4f73-9530-167b34cd297c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Delete Messages</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb915610-1e79-40a1-b4e2-036fa0b532ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2827c3-e8a5-4dc8-9b17-b7c914044966</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84d722fc-5bf8-4ea1-9bf5-cc5981c2f53b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22ba9eb1-3177-4acb-bcac-e1e7f8f866e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Remove Google Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b974600-0d37-474f-951f-46495d618922</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e065095a-179b-4db3-be66-208a53efb282</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a80a4744-5582-4e3a-9ffd-0f404bd1d50d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e468ced-1694-41c8-996d-0472fcbea69c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Rename Bluetooth - IO Pro Automation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b0b36e7-b505-47ad-bddc-dbff92b7c4eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b98128c-896b-4fdd-a902-2bbfd1492b7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f86e96da-a9db-4cf8-bccb-ae15c8d4c8c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f42d52c7-f171-4ad0-aa5d-3a29eac2781c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Rename Wi-Fi Direct - IO Pro Wi-Fi Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>065c606d-7070-47b2-826f-fa9ae123e6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc931d6-6e09-43f5-9df1-49ea6704c0a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b9fa0f2-37d2-4e81-aaf1-a2a254a28bac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e9e0ba8-fa37-4d84-8dc1-3702ae1f759c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Rename Wifi Hotspot Name and Password - IO Pro Hotspot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09bd79ec-7d35-4135-ab1a-a80d7dccbb41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff7aca59-36a4-4aec-b49f-ebec0439e32c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d894bc62-084a-448c-806c-33f85ed4aadd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>050905d5-b730-4771-84dd-23060483ae2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Reset options/Reset app preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77d2fce-0bb0-4957-a706-a33a49153c3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92b0405e-0616-4497-91ed-9f0864097c70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fd2f24c-cce1-4f90-8f5d-5bf42f857b2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8cf772ff-5e37-402b-aa32-9ffdfe38f05a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Send SMS to IO 3D SIM 1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4bc6107-b6fe-4cf1-b1be-aa7688afdcb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f540da-a507-4458-b49b-db413ebd4256</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba7b53e-0b27-406d-9070-0a007d70a9f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32e67906-e5a7-467d-9dc0-93faee87c4a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Send SMS to IO 3D SIM 2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56010170-5315-4e23-967e-6e3d64eda751</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7ef27ce-526d-4783-935a-ac69ecdb80e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc02c796-f30c-4e09-a2bd-3f7b614e6e54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe54c96b-9756-410a-a795-8f14f6043562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set Lock Screen - PIN 1111</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7ae31dd-0464-4858-b11e-fbb9db97c16d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dcd0757-a666-4900-9141-45c1d70fc8d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b8c3ac-7cf0-49f4-9766-99435b32fb8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2374228-5d49-4752-9e91-44ffdf6aa17b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set Mobile Data to SIM 1 (O2-UK)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82be76eb-25f7-426e-9c86-db1c11672520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e461a1-888c-4fb3-ba06-2690a9cff94f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b58c65f-811e-4b54-918e-b1f9d9bb7ac7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>033dbf5e-ce3a-4638-9351-2126b9ed9eea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set Mobile Data to SIM 2 (EE)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23e0d53d-6b60-4f6e-bd0a-553816454971</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b06c429-17c2-45ab-9d44-eeb2a79bd4f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>649abee4-6fdd-492d-b247-5637968fb20c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f0a2e52-a08d-4368-a900-fdfb474bae68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set Preferred Network Type 4G SIM 1 (O2-UK)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f00323d-8a65-40d7-a035-fef453a520cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84db9456-f27b-4e63-8e90-34c8fd85e21f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>655a9e37-98ad-4484-ad70-d1c723aec773</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03e773d8-fbb9-499d-863a-545373ddf2f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set Preferred Network Type 4G SIM 2 (EE)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15665584-4d3d-4030-ac6c-b785b67778a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>160b3d9b-87ea-4bbe-b3ca-fa99284983ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87e56635-ec8b-4838-86ef-18738341d214</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>011c864f-2851-4b06-9cf3-99c54b60fd02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set SMS to SIM 1 (O2-UK)(TMO-US)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>465414df-b641-4d8c-b5da-198c14cb152a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59e4edd8-0c0e-468b-86f0-4b3bf8e52712</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebd9048b-4c85-49b7-9b0f-cf73c5d29566</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11db4cba-c20c-44b0-b0d8-702ec042c513</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Set SMS to SIM 2 (EE)(ATT)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba8842f7-0eef-4c26-b01b-6aed35df2159</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b003e65-d3e8-4bc0-b72f-2de27316f420</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ddd82fb-2224-4685-a6b7-32ed4fb27679</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68750aad-9a27-4283-a06c-2c186a6dfb2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Sleep Time/Set sleep to 15 seconds</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>370c0ce8-6131-4aa3-9294-4867fa0a7468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b1874bc-ccac-4651-a764-5444da1dbece</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e30e309-f7c1-430d-b1ec-640d6bc74259</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ba43335-aece-45d9-a117-20dbbfd70037</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Sleep Time/Set sleep to 30 seconds</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cacfdaca-5373-40f0-9e89-a23be7bfd25a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9fde8d6-2afc-410f-94eb-40f9e44caa04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5350c57-60a2-4958-8efb-23c81982e8bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e066f64-e263-4eeb-93fd-489d000c128a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Take Camera Photo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9241d98-6849-4dc4-aa99-a3a9267bb79f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df35c78e-0964-46c7-ac5e-6521c1884bab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c2ab57f-2ab9-4f1b-8f4a-c2e1dec3fb9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00feb8e5-94f3-4fc6-a111-c3986c67b040</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Take Camera Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6d276c2-939c-4360-90a1-352732e89e83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf143b81-33da-4c3a-a44e-a644d3cf4d96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fd7ae30-a01d-4d69-bae6-07c9cea9434f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfc7c78e-9de7-4073-9065-039d106840ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn off Bluetooth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b3ca18e-76d0-4f4b-aedd-e7645c0bd4ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c6d6c08-0f7b-4375-a60f-9199d4c37c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d61e4b40-9514-4c96-aa62-9935fa21a2e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>848625b4-5a7c-4280-9ca6-f81634b40dea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn off Mobile Data SIM 1 (O2 - UK)(TMO-US)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a7322bf-6daf-447a-9a80-3da95cf94732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e75e5081-9773-4dd7-9ac7-26269c56b5e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f57e084c-8a57-4078-8244-9d3531eade42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1d61a1d-adce-4de4-aeb8-18ba57abd4c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn off Mobile Data SIM 2 (EE)(ATT)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b66b19ac-52a5-4f76-8159-127195930669</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52fdce5e-eba5-46a1-a54c-e8074b37d62f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56b11fa0-55f5-4bd2-9ebe-a9e77603dd8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0117c35-471c-494b-8176-97eae83d2f8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn off Password Lock Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>425a374c-3777-4770-8003-760a953d4629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03b1189f-0621-4fc1-b8fa-e32db2c4cd93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e2ada51-e7bd-49fe-af4a-88d8f688fea0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f3ee692-d90d-436d-b655-c070124120e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn off PIN Lock Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de50c2ea-fdb8-4e20-bc8f-f9ee8639ac92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57158fad-28ac-45f9-a3a0-e839594fb7bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35522479-cc78-4266-ba79-c2e669b1d2a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7011a5e-5538-4347-a913-0dcc72990ad7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn off Wi-Fi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1423ff88-29b6-47d5-9224-0a987a349536</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d91be24f-be5c-44bd-bdcd-d8573c18dcc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8286252e-91c3-4d06-9c8a-87a9b8108aac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>385a7efd-5d4b-497a-8440-72fe5478427c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn on Bluetooth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd537a68-d94f-4645-ae61-d6c11a45df76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11763b9e-f3f9-4e0b-ad7a-344b65216b6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de2e19dc-81df-4f0f-b2e3-efd57cbf6dd6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffefdf63-31fb-4a62-b3df-6474abe3b007</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn on Mobile Data SIM 1 (O2 - UK)(TMO-US)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e4d95be-5dbf-41b3-b602-8eea0cf6d1ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6bd005b-9a6f-49a0-98c9-b6dcf09bc596</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>093c8a7d-a104-4fcc-a0d1-b012d340431f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6876261-43af-48e3-9afd-848e4c1cc132</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn on Mobile Data SIM 2 (EE)(ATT)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23227cff-bf5a-4b85-b94f-42cd92dfd2d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b0c1253-f581-47f9-a672-5b2231f410cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f31886c9-3e51-4181-9093-742add9900e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a067184-fd55-4793-9008-fd2ef3d9b6c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/PRECONDITIONS/Turn on Wi-Fi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0973a52-d42d-4db2-8df6-8f14bfa85ecb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ad82aa0-50ff-402d-90e3-86ac11e02d53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f18e390-d3eb-41a2-908f-165071ed316e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
