<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Ovi Settings</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f7a4b1bb-ccbd-4821-8d5e-4de2857d6af5</testSuiteGuid>
   <testCaseLink>
      <guid>0f6b5a3d-35b0-4f7f-8b51-04b64da3ee5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Accounts/Add Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71808f0-9002-469a-948a-0ea96ca6f9b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ecf96f8-a800-4116-98db-0c79b9fa251a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3057aae3-0e66-4701-bc0b-5ca24584000f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06b15b8d-fe14-404b-946a-bf07d65e7c72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Accounts/Remove Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>068efb37-75e7-4d60-bb3d-2c0ca70be680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c52c1ea6-4ccc-464e-b667-6d89683990c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>522142f1-9a69-4b8b-a046-ddd59ca8e50c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14166947-f233-4d86-a17a-6e108a87e198</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Accounts/View Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96352085-1cac-42c2-8561-c18b83194792</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf36c15-adf7-409b-b03d-61a4da04c8b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4082d35b-70c7-4b92-b001-884ce3c03efa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dcbda35-c7c4-4354-bc2b-ceca61d06a0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - App Permissions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79a8b371-382e-4735-905d-f33d5d62834e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e9c6975-81cc-44fe-ba16-503fda6def87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daea9181-0870-48c0-838d-e9e4f3d0dd43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e59903fe-874b-4115-b920-28fde5f9d353</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - Default Apps - Opening Links</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>313e4fad-f6ea-4be5-8c63-7a9dbac425ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f7ceae7-6ff2-4fc9-9abd-f8846ab9218d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6afbc758-3cb0-4965-9a79-d453744e5947</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2132247a-1b6a-4ba3-8852-bc096e1f3d37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - Default Apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c7a2c36-ad57-4f43-80ec-2a0f1013ab58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbe354d5-67aa-4dca-8689-29e379740d31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d3efa08-d6a9-48d9-bfaa-48ae59906808</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>935ecb80-4a4e-4593-be38-43f11fd8e370</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - Emergency Alerts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7828f40a-9b09-468c-b137-4a0d2be3bc22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f071a5e5-49f4-4ece-b1eb-cfa567a97160</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54604531-3f59-46c6-83f8-3328f8212972</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>742708ad-7911-4802-8b95-3a59710c3b2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Disable App View</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1df3356b-7803-431b-9e44-a7a5d43e080b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>376d23d0-208c-4362-8bea-45ee946ca728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>400d5eb0-e055-4316-96ea-8ff6e8217423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73e775c2-2877-4b44-928e-6ae893920a0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Do Not Disturb - Turn On Now/Do Not Disturb - Turn on automatically</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c9cacbe-f652-4b25-9c6d-20f392b51e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee82769-f6e6-4541-9da5-3e8e5bc668ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b00855-653b-46cc-b2fd-87eb768bcc38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bb05650-950d-45d2-b1cb-f27920235c9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Do Not Disturb - Turn On Now/Do Not Disturb - Turn On Now</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>540a3fe7-a8a3-4894-95bb-e166c0880a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d536b6f-a8ed-4344-a23e-005363b3f361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b970014-c51c-4f22-b065-c3fdcfd21643</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cffa5c06-4fd6-4f4e-888a-aa49aba1658b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Notifications - Recently Sent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19a1eaee-cea5-44ae-b3c6-c0fcb72e617b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ebb166-47e9-4524-bfd3-8be0e7022150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d86eea4-8d21-44c4-874f-ddfe761de129</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51462da4-a14b-4e4c-8758-1e83f590de73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Screen Time - Set Timers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b64a1a4-14f7-4929-a7de-52526b6c055d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0daaa6d6-2154-4ee5-b38e-3bfde3b299f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eac67b0f-4210-499b-bb98-95ba7826bae6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccd7a5bb-286f-4ac2-8592-c87eaf1b9e9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a5be1f0-364e-40a9-a6aa-7c97c05beff1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8986e12a-500f-4ba2-8291-d33d87965848</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/See All Apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e85fce34-6f6a-4293-885d-0cad8f753006</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f1512e8-0317-4363-b4fb-c2099cc50b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c33f9fa5-5e5c-4aec-a003-2e07f14ca681</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3768d52-600f-4d40-9a54-328d07f7234e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Battery Optimization</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ac5ea51-e25d-4348-a922-e3d67e520ba7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143c2bd2-6db8-4835-8864-718ae370967a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1601456d-927b-4d78-9369-a2622334e732</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>15c10158-e79b-4a56-b425-acd392c8e550</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Device admin app</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93ce381a-bb1e-43ae-8e19-f5e401ea996e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffcdbe8e-e378-411a-87b8-ae9b8f99e5dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcc0cc7d-1a3b-4107-9f1b-fe0eccf9d1eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8de1aebb-7d1a-41d6-9289-cb4ac850c526</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Directory access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff14b572-47c3-4f80-be83-ef8535a69cc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d73649-7ee3-4b95-a9d6-536d7ae8f72e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5db77e2-5af9-4591-a485-de7ffbc01a70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8d1ecfb-1641-4e21-a7b3-3d44a204611e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Display over apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e37499e5-9044-452f-8642-6b7a3cd7a563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcc62f9f-1baf-4afb-bbfe-2c487b70453d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ef19d8-5808-4b04-be2e-7c80be9a9829</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bfdf8cd-a850-4836-81f2-517b5316c428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Do Not Disturb access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c871f0f9-24a6-4181-ac94-be833796def3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb92381c-f0dd-4fb2-9e81-4b88764fc627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>264a43a4-ca84-41d7-9716-063f764074ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9885b1eb-881a-4f20-899e-9a6f6fb5aef5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Install unknown apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>398b742a-a824-4a70-8069-e75048392e72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae73eda4-b2cc-4a50-b97a-5790c7eb61fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c43affaa-0bcc-496b-ac4b-c8407fcb9be4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81cefb5b-c808-4fdc-96ea-620c0614e772</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Modify system settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>645e3faf-ba64-4ce1-b215-b5bb0a95c05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a599ca4-42ff-4aa2-b4a8-78ccf1588381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f3ab96-6a2f-4dc4-96e6-519f9b502096</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da3aa420-0e9e-4bcf-9779-c9f090dee115</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Notification access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1bcde10-f997-484d-8273-b2413bca940f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7108dd08-7a8f-4c3d-8b63-f0ff013b889c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ca1089e-57cf-45c7-8270-4d515efde9fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bcb30d04-3ddf-4151-b1ac-8dc57f099928</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Picture-in-picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d65e9d1-242d-49b5-b1f6-ca0d4cd0648f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b6a28b9-e0f2-4773-9f84-edf8e3f4571c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b6c77b-031f-4c3d-a077-6284e5ed7f88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab1dc7b2-597d-4d7c-a347-c2f2f5f94d8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Premium SMS access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c88c229c-ec60-40c5-8f7a-122057788cf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98bdce63-4e82-4e68-8457-057a73d1aa16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b767a205-7cb9-4e60-b64b-73d38cc4a958</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8575a9bb-6f99-4d14-8aa7-bec715bc7699</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Unrestricted data</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03b253db-0336-44e7-a5d0-651b787ffba4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ecc96a2-2d9c-4522-989b-8dd65b9dfacc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>297eff45-1d2f-463e-a362-603230b1666f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d4817af-034f-415d-9bae-d3dee8d5c981</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Usage access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecf085af-506e-411f-a7f2-f0b034df9926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61a7c498-265d-4ff7-ad2e-b1c7c1489cdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa6ae219-84f3-473d-a80d-7a98d3742e5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26823d72-122c-478c-a78a-f34073f3dbe8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/VR helper services</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c0b1321-7857-4e0a-8ff0-db986c96c96f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96bcf4e5-f0d8-4184-b214-99d2128f958a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>507c2573-d5ee-4da2-a089-7b777bac55eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62d590bc-64d2-4939-b266-8ddf9f75c835</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Wi-Fi control</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed41c76-77a7-4461-a7fa-d199e9db28c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34324b91-5729-4715-9d88-c91b322d53bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e82d7c1-7399-4c61-af9e-4c6bb4761a97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82a438f1-42b7-4695-93d6-74ee8b731d4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/View Recently Opened Apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b382119-0c57-4f9f-b866-050032028f12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e56cfa5e-5e62-4f1b-847d-027361b53a01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>044ee2cf-6ea2-419d-88d0-66deca9a8dae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3afc03a-f4c0-4211-92aa-5e90c5ac034b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Battery/Settings Adaptive Battery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1bfa2f9-23a4-4bf3-a30e-d3368a085434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b8892ad-0f67-472e-b305-184454b69683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8d1d16d-5c2f-47e4-9638-e1d079e647be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea698957-783f-4d06-8279-3af16b3b3436</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Battery/View Battery Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec4291aa-8d83-4b6e-9787-0634593e0b24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5343da87-348f-46a1-9293-a7b78f9ad1e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcd736c-3a9c-4a2e-86a3-169a0a96c5a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a350b6f-2db5-480c-a0bb-185a55a3e1a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Digital Wellbeing/Manage Notifications</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21277910-a4f9-4230-a7a9-c252112eca4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed818a93-8055-43c3-9760-8e55b1b66e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d9bec0a-5390-425c-a708-1434104fda25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c61b187-2d31-45ac-8e7a-93da8227fcb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Digital Wellbeing/Show icon in the app list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>495fccff-a989-4957-9acc-b35e01d371cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba3d0983-18e5-4fcb-b12d-153f9f321ee5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90f8893e-0153-414b-8843-63240e425336</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0820dda8-6940-4aac-92a0-416e68685379</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Digital Wellbeing/View Digital Wellbeing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13394281-3a90-40eb-8ac3-cdff863b2e0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa720567-193e-43dd-8cfc-f5b92f9bc387</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a98c610-0508-49b7-91e2-2aab7cedeff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba3170b9-4629-43af-a049-912a5c931042</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Data management</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95af7b99-13b5-4d29-8249-22f3275c3643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54da181c-1091-4baa-af32-b896cc90cb40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed06ba9-3fae-40d0-ad2d-225c67479fc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>869b5838-55de-4400-b339-f8f9b0ee26d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Google Backup</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78d205fa-6c35-470f-9113-3d357957f6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63bcc94d-bfdc-4b09-93ba-f746144817de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fda0c00a-e473-4ec8-996f-ec1ff65a3e78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6369fbe7-4ad4-4cc0-9b55-27388c83e66f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/On-device sharing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff26b7-7628-4b45-8d6f-d163abd83705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f515975e-0ba9-49a7-ba46-6e4b849cc213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>343d4b13-e8b7-4f3d-83da-f7de0507b642</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be02a467-287f-4218-8bac-6da64dbff776</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Restore Contacts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4881718d-cd53-4a7f-a76e-d85fb7f91e03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c16c5803-4e43-4e67-8dcf-bb6f4ef541de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bec99709-a334-4562-9362-6327c4ba1f98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>773f6871-1e56-4c6c-a6ae-a5c2c7301e15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Security</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a6a165-a7f5-4736-88fa-513b8f2d4d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c8c7d96-90fd-4aef-b12d-0142f5f623e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43fb3669-3468-4aba-af7b-d9e9ced2bdc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fc1178c-7054-4f62-9157-b8cd3c05dd7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Service - Ads</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e636efa8-5cd3-4836-a5f5-d5533e6ce088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4caff1-a825-4e46-9351-d31e9ed2e8cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc976877-5a2f-4e2c-8153-597c4d997f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0657ea82-2766-4efd-8e12-7cd369366551</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/View Account Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07873038-df84-4b78-9d0c-fe5a50ec79c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03ed12b9-c439-4a08-8583-645bc30eb92d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>381ded3b-dbb8-47de-a256-5cc6e53b4122</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0275478-9514-4054-883d-bcea57ccb444</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Aeroplane Mode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a65d6f7-2aab-4cda-afaf-9294dc68d420</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47b77f09-cd2f-40d3-840a-808c892b0e48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>634eea75-a828-4986-a3e7-481ce9b1c2ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17aa7e0e-1ea7-4b8c-8a2b-fc5950a9cc72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Data Usage/Enable - Disable Data Saver</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d316de0a-fd7e-41b6-a4b4-97873a22414f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34361f32-d8c8-4bf8-a378-dffb213c4c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e2fff5a-3b2d-428b-a55b-3a9d3443c946</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86e6da63-93c2-4ec1-aa98-8a08080c60fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Data Usage/View Data Usage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>babab873-c242-4959-a07e-a9fa28fa6ecb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88524cd3-ab89-43ee-b04a-ae90e597d7d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a96b84e-f063-4d8d-845b-58e0c4c129bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a90d7d36-3e29-4397-bf99-734f4a5f3a04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Hotspot And Tethering/Wi-Fi Hotspot Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>734a5cc6-d70a-4653-be00-b1587a53fd74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26ffdc3-5530-4750-836e-426fa942840c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e545b44-868a-4874-b691-62349fd25965</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85b6aac8-8709-4cfb-a3c2-75fc66264efe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Mobile Network/View App data usage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a4e985c-a976-4c99-9da4-7f903804ec1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19deed42-7f0d-4e89-a1b5-500ac386c1d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4750396b-bb90-4db5-8d0b-b322bbd1b4e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>960f7b81-2039-4322-9dc7-bb8360b73cf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Mobile Network/View Mobile Network</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18df87b-4e21-4afd-b32d-a653ce582386</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcaa704e-3db3-479a-bf27-56bcb3c89223</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a26f6d76-9745-4267-b53b-66170f3ba506</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>627623a5-4f78-47c4-b7ab-7de269d2b2fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Private DNS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1f89b42-ffef-465e-a84e-de778ac6ee31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d01034-1752-4598-8091-976782587de8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed44ce79-6c11-4930-8105-ee994e370511</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de9decd0-86b4-4c68-9496-f30af509b955</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/Forget Network</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7fe654e-85d0-4f8d-befa-54545b4df9a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c42321b-2cc5-4dc0-9ac3-cf41e376ab25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f94b3ad-8eb5-403f-86ab-b191e77969e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddbe479d-21ce-4be4-b41b-bcc8a7bb3cb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/Incorrect Password Wi-Fi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee962b4d-6dbc-49ce-b634-000b318476b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94931a8-8c45-4303-b1a6-692b594537eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>408ac1ce-3bf5-4095-8d09-cfaaacb82fc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac8f89cd-b6e3-4559-8c01-ba70aa2cea92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/View Network Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0827ac9-a05f-40d6-b243-8c61a43254ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5930f83a-0dec-43d1-8b89-7cf95dc8f370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69a2a6eb-a17c-42b6-86d1-5766fc155771</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58c90c19-b87e-495d-bae3-6e1a244b57eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/View Wi-Fi Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>effa97f6-9137-4699-8a8f-fb0da9fa1a58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccab2dc7-e774-411b-aa64-d32c7a66215a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3358ec5-4eb4-4d45-8bec-8833f9e78015</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f217fd06-76a4-452e-9d66-eec613487e8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/Wi-Fi Preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d5c99a7-02da-4b64-b5fb-21e3421c1115</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba38ced3-c9f1-4192-b310-dc0666567091</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a580d70-5c08-4ca7-8129-92783e61a784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d6ec17a-fdb8-43eb-afb1-13a2b4f80b89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Device admin apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e89fc6-64d3-4012-9d96-fd93aba739b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d9d771-bec7-484d-9bd3-b012b9f4ae72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12e4c408-6e60-4c34-a028-177ccacc494f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8fe7319-2994-46c7-8d30-eda3f34fe7d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Lock Screen Message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>396073bd-0204-43e4-87f8-e63673f3328d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04e4174e-aadf-467a-930c-b2726ce062e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62f64b18-229c-48ff-a588-0bdc32c7ebbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc0d2c61-6fdf-4be4-83a9-3c1ea389ba55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Encryption and credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d09624fe-866a-45d1-88c0-65cdfb1b3674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a9aac3e-c571-4db2-a9cf-c6b34a476585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15931ee4-9284-433a-9313-f83d8abddcf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9759679-9ef3-4f89-9d7c-cdc1c0beb40a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Location</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d564d2c5-112e-4240-ab4e-881096677c32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c79a3a29-519f-4f96-8579-c514d4902e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dbaf6db-3828-45e5-adf9-b55edcaf91ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd83a02e-04ca-4b4c-b6a5-d5afb3fd9a37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Screen lock (after setting security)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e58102a-f924-4602-beb1-9332c72ea116</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d903211c-c619-409e-9fdc-5cecdb80f1ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57fe09c9-9dc8-419d-a569-d1dbeb9aefc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f63a8318-6851-486e-a650-ee1809f180ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Screen lock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5c466e5-82df-4460-be0c-082f9aa057df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ea7ade-584f-4bf5-8a0b-dbf6a82ec01c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5de5b6-0ac1-4d11-a24c-ad6f5409a6b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5a7d58b-b93a-4016-bc83-c822648d3d03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Security status</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2faf00f9-0a2d-490e-9b63-d7bab1ab5777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0099a6d7-6693-46a9-87df-0c77ce5049cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aebb4ea-1e0a-417a-8906-cacf71608c84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7025428-e236-4cbd-80ba-5194b9e03735</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Storage/View Storage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941d3b0f-85f9-4fa2-a9f0-408fb5e0a908</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bf1e039-68d6-4ed5-b2ef-0c56defc6ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63921b26-e4e5-49e4-afcc-be2ef1a16b7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebb97e4f-14e8-451e-88cd-1a7728ffde3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/Add Emergency contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1495b1e4-594f-4665-a9d2-b1b786128c1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3044bfbb-fcd2-475d-8ad0-4e8ae604a7a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ed34db-efb1-4239-b87b-12a599f0f79d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4044a49-aac5-4553-8cf7-331cc0092eee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/Change Device name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ccfe6ca-04f4-4af5-92b9-f27fb758be87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80989b6c-799a-4e36-9202-2e93cfb3d36e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1848647e-cf16-4dcc-acdd-f8ac135ea150</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e88ae0f8-4492-4bec-89ad-c8b1ab0ffc95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/Edit Emergency information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41edf871-681a-431f-a9de-d2ea5c6e9eaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c76d5c25-c7d3-44a3-a597-930ff9d324ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28b70c57-40be-47e9-aa85-f0a67cf760c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>425c7fb3-e760-412c-a4b2-2ea844653f65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View Android Version</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92882168-b018-4e70-8aa9-812a98592114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a10d4fd-2370-402c-a2c6-5936dd309489</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3d78ca-0348-4545-994a-97347f7afec0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>869fdfdd-0684-4d19-9e07-a0cc18574a95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View IMEI (Slot 1 and Slot 2)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f0f3dd4-7758-4661-a8da-ed4682525d9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59deb499-9632-44cc-a771-aa15b1e60458</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c418209-5063-45dc-adc2-0b26c1bc1bc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>250f7c07-fabf-45f7-8b23-a38e4f60898b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View Legal Information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bedf8621-3285-47be-86b1-a3ef408817f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>498a1f2e-101a-4666-9fd1-8045aef3e6ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7154a983-1649-47bc-861d-11eae44aa99f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ff00610-f9d6-46df-b09e-7445b2d71177</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View Serial Number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>559c0366-0957-43f8-833e-6a14a10464d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1040acad-71d6-4c65-a219-ca49d26a30e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1acf59f-93bd-41ca-a7b2-01f77c460f16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39c4ab30-2840-450a-94f7-7e63e7fea28b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Backup</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0435c360-2d6a-4e01-a4d1-0fcaed8969b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62a3392b-3c33-4f0a-bb56-56fd3e627334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90288155-cca3-4fb7-afbc-a15fc7ca94ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23833d3d-0f55-411d-848d-d371ffb14c3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Date and time/Adjust Date and time preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>924869a6-1141-415c-8cc2-63ac2c425fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dde99fa6-892b-4d08-831d-128cc1f8fe71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9189699d-2f9a-4e90-89de-39f48116126a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>435755ea-88b3-466a-bdf0-ee8b9197d39c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Date and time/Set Date and time</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2ccb60-2b07-4b60-a8f2-c20cafa12362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff813350-8ea4-4db3-b81f-096689f9db05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec8e0e5a-9549-460c-90dc-14af842f0879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f69d5f0f-6c3e-424a-a4cb-b78d6a685384</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Bug report shortcut</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae3c7982-53e2-41ce-8c3a-0c3d6a20d278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c08a1a26-ced7-43c2-be4f-b1f7b0031617</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354d0a31-2b01-4f6d-b139-a30d8cf3b56d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1eb4184a-0af3-4dc3-b0d3-5e0a66281075</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Select mock location app</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac34377d-4ed3-45c5-b1dc-3706b048b1f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a197822-cd59-46d0-9d44-3321abc2b20b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b74ac28f-cec9-4c12-84ab-9bad75287520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9929b5a-5cee-40cb-8328-5a31883a0b34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df958ec8-62f7-4c0d-8710-addd67b94a49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6af4e493-063c-47dd-b6c3-3b6380ae5155</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Stay awake</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65270204-9111-4ef2-8146-3f780d58b46d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8818f585-ef13-47c1-9522-a7b11522e5c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86148b07-d301-4dd6-9ee7-325c2af0f5e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c0a09d0-d100-4137-bd30-8190264846a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/System Tracing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb87ae6f-879f-4d89-acf2-86d74ad7e01c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8474c620-d419-42f5-be37-d699d9504e6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>161c1c6c-94cc-4e7a-bfab-926c53403788</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5328e078-b458-422d-9762-fe87b67a618c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Take bug report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>969a9a2a-b699-4288-8ebf-c4724b4a5ac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f72c925-c326-4fbe-b1a5-a5aaa6c97c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2bf8c44-487d-4f17-99a8-f33a43e1256f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b7fe69f-d50b-44ea-9ca9-8084e40687f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Add keyboard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad0c0e2c-e4a5-4b9b-8f82-8c2916d241ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0b16b9-cda5-45fd-99df-0a73dc6a280b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44d7a2ff-af3e-4f78-920e-1f9f11938b99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2513102-0666-42af-a434-fd58b184a252</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Advanced</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdee5dee-5187-42bc-af72-97ecece679a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669ec3ba-b16a-4010-8058-5d90878367d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad3cf948-c926-4012-90fd-c787cdefd61e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7095608b-c998-4ffc-b2f0-0f0a1191f904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Dictionary Delete word</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e6940d-f109-41bd-b352-5f6f35c5039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d0765eb-9a0a-4dc3-af0c-3d61f417b8bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ae04e4c-2f62-4067-8377-e32a76905b00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c7acc9e-2ec3-4ec6-b601-7e42c9178bc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Google Voice typing - Support</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4c71212-a9e5-402e-a6a9-4f1e8d37121e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e86c14-a027-4713-9949-576ad40972a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6832d49-39ae-4986-8aa1-cb926976c043</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a50d00a9-242a-4e3b-a9ac-bdb382ad94c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Offline speech recognition - Auto-update</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fef8810-c7e5-4d67-a7c6-6da0960fcb11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc3c3290-4064-4b73-af0c-d4dc6978cff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31c03aff-2496-48aa-9ed1-e3f79315384e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fc965fd-4525-45c1-b879-55f5832f6b89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Offline speech recognition - Install new language</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7808705b-c9df-4b29-8500-35787ce14809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fe2a3d6-19f0-4ebc-ad53-c9a7baf9e6f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b8fbd3-ca87-4570-8a08-b3f7c529fcb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>945c3436-566b-47f0-a08d-1efd3995310a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Offline speech recognition - Installed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dd061d2-19c8-4bbb-bde6-13f902b86362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47a75795-8327-4f26-a360-571d4ec77cd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef85b4d-571c-49d6-ae6b-73b1118f996c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d4f88e7-e767-4909-8454-dac8149c9872</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Input Assistance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acbe2bee-1b39-4795-8d73-9f9778efb6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>692632f4-4a33-4915-a27f-6096b41e752b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64aac18-5963-477d-bd20-06ae1c34e0c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54dbd5d3-20f2-4304-9d36-ed4c478c02b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Multiple Users/Add User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0327072f-91e0-404d-beec-77b73f0e2715</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac49a8b6-6ee7-4708-a205-52ab1ce490a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06f0d9fe-ee42-48a9-bc82-adab402d189f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd530f82-2a97-4b77-bc06-9648698d3c77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Multiple Users/Guest User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c2f172e-52f5-4459-8a8d-8229f4e340d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ab664f-7648-4f0c-9d28-a09e81378f46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f470e3-8bf7-488d-a161-028e1dcbe585</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dbeb4c41-5729-447d-be0d-8796028d697e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Multiple Users/Remove User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63a79c13-e9e2-4eb6-a1e0-9ea8c3b064b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ea5262-12bb-4b2d-9202-fcc9577f4e41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c31572c8-876a-426a-a4e4-045c154e1e37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94d1516a-3fe5-4076-851d-de520bba81c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Software Update</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58a36522-0a65-4a50-85e3-49ef62d85256</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8745e46a-621d-4cd0-a39c-59be4be89f80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d15c65cc-562d-4cb6-ac5e-532a5f1dbb81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1b37b6d-139e-4f0f-9ef0-884379d5bd7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/USB/View USB Preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77310f81-f202-4849-b4f0-77b42cc6a38d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e20c9c93-f1cd-4ffa-a8f9-b247e6a173c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c83c892-228a-4be7-b702-04af25f51f34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1011f82e-d93a-42f6-9584-a871e4f8f9be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Verify Internet Widgets</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5514e609-f28e-4298-80f2-a82d36725742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c93a84f-ecb9-4329-82ad-b8752a67a102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93bedbe-4c3d-45c5-a5f3-1eec0983f7da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a56820b-ac48-4d80-844f-11beb8979533</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Widget - Add Settings component</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10f8d9d1-b387-46c9-965f-33a754a6ff8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f1cb50-4573-40ba-bb7e-2f74e0a3fd66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3dd74d-938e-4a36-a843-6394d69a02b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56cb8355-5417-49ae-a651-8c4a972e2912</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Widgets - Bookmarks</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fc44875-c08d-4454-b5e9-870490b2102b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0489b7fe-ea44-4da4-a843-2055c46b7260</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e412f97a-f823-496c-bfc6-c30ec1d6aa6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6c59ede-30b2-4ce8-be60-0e42255cb40c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Widgets - Clock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b2f7ba8-65c0-44fc-a0a2-1df589979e25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb64d87c-c13d-4d27-878b-a3bdb66e4118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d4302c3-f052-4531-bb76-5dc5b76612a7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
