<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Bluetooth to Languages</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>adc94796-0c9b-4c1e-883b-3c9a0ccb778d</testSuiteGuid>
   <testCaseLink>
      <guid>3e3d2ee3-e894-47c0-abf6-8345e45732d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Bluetooth/Bluetooth Enable-Disable from Quick Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d4b270a-82a7-4a77-b39e-478160024656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84894c1d-11ab-43dc-96ef-9fad592f418a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05e7af6e-c5fd-48d2-a57e-4f63244b5a9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe2738d6-8107-4bfe-8b8f-08c17c82b906</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Bluetooth/Bluetooth Long Press from Quick Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a33d735-5770-438b-91aa-22f53de5cf0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaa6a270-6e13-4f18-b4e1-400ba470a2c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b8e1e8-2b44-4a88-b857-67749715cbc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a059df1-499a-43ca-b02f-58e518b90460</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Bluetooth/Bluetooth Toggle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c9a53ea-dac1-4a0a-9b17-92c339951b7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c85967f-b13e-4a23-9898-5c904786b4b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc853272-0ba7-42c0-8610-469804d98470</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7efcad33-131f-4b1e-91c8-082c1c83185a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Bluetooth/Bluetooth Transfer Files</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dba2334-6a17-4242-bb84-58c9f86aafaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26073903-f6b0-4ddd-91a2-348e60caac0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e7c2921-119a-4ae8-9167-ab183900c7b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2faf7830-bd25-4d68-8219-bb76d22b7dc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Accept Cookies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b7b26b8-c9f1-48bd-93ae-11f1751bd80f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62116229-02b8-4c75-9b90-ed3dafd3e2e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a00710e7-1bba-4c8f-9a58-95cbf70c672f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf12ca8e-50e9-4684-a1bf-90e05bde9fd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Add Delete Bookmarks on Chrome</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49faa42c-0f9f-4357-9d04-245d70386d0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c347090-0d87-46bd-b764-cf0d16a95c12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7103f59-7ce1-4d1b-88e3-c282bf192ed9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bc11e89-7b34-4762-bb61-11d6087b9529</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Downloads</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f369b68-6499-4682-bec1-5f54282b4f37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5025f640-98d1-4bfa-b2e8-8a2f1ed57524</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>715b66d5-29e4-4be8-aa4a-b9b334d95d00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>203e1db0-a485-49ad-a45a-04619d9db915</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Email Hyperlink Opens App</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd910a5-3383-45dc-876f-108e59bf4f9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d42de3-8ba8-4dbb-8cea-3b6f8e9c3fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>863f5769-5a31-4b08-b56d-8b639ff1edfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cf9ea49-30df-4b2c-b338-e17a8b213eb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open Google Pictures</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09442d78-3012-4c28-aa74-61d7847e007c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e03ae177-7851-4eec-a674-b22f0b4d0447</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76bd1b5c-311d-4990-908b-c0e27b16dc43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7df03eb-5ea6-4d62-ab84-bee6efd15bcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open Google Videos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2deee18b-745b-41fe-a7e5-a1cacb3684b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8756c79a-b1bb-4b5d-8bd5-3bc348f61191</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e8d358f-0cd2-4050-bde0-6cad584c37dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b47f18e-bf6c-4d79-84a2-9eda404293cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open Maps (GPS)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93c46642-f8bb-4888-b915-d2b8703913bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>580f25cc-0ada-48ba-8f3b-344d632f5dbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fa2ee62-4436-41bf-aec2-4ef652a41a6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8de365c-4474-4c00-8698-9334f8396c2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open News Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04dda822-4607-4c9b-84fc-b32c1f59ce57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6823dca5-36e7-436d-9e93-b5b013b111ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2304581a-f134-4905-a092-cb4d9c765943</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87c40f92-1150-477a-86cf-d368d91ace2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open Pictures</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97367b73-950c-4a4a-841c-9d782471b9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>080cc90f-0890-472d-b50e-31695e93b2f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d1cf3b8-b29f-421d-ac95-f39d237a64ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa59c161-9fcc-4e56-bd6e-e65b8958331b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open Videos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>874c0583-40af-48fd-813c-2643da67acd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dbbeb75-39a2-44c9-9638-44efb8579aa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58887246-2291-4254-aaa8-ad01e944f6f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4829071b-3adc-46a6-9b2a-80cf17caadb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Open YouTube</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd7a5970-6468-4c0d-b269-a9e6f404d816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69c18ff2-2098-4c8e-82ab-d553f1275341</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f6f32aa-cac9-4787-bba4-5359d8d6b98c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>595e0ec5-35e6-4e68-a935-25f364e10e87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Search Landscape Mode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6df12cf6-aa4b-4988-be32-e4229e337799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a700a47-9989-407f-b652-8ce6d9c00397</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd74c524-7f25-4cae-b77a-a330dbb8f9ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>197ff624-07bd-4383-8980-ef7592438fe5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome/Search Portrait Mode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc0be2af-0571-47e1-a16d-070e06c33849</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>073b502a-ba08-4842-a5fc-2f09be551d5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b077702-67f4-43d3-9268-38ed5761a567</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d7ac40b-5c61-46cd-86a8-75cf43631b51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Chrome Search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>104973b8-7f08-4a4b-b2a2-d8eee2aa0696</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5398990d-3c50-4c82-b6cd-6c3c326d273d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>118b3ff4-1865-491b-8551-b360c85c02a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb10a827-0409-4ef7-8e08-75a50f301b4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Launch Browser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24b28eb-7f00-45f2-bbab-ca8c48b1431d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8846d478-fa1d-44b7-88a3-6387af7b7de9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfefabb0-2911-434b-93f9-ada22170fe2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98ee6e64-f5cb-42ad-9d3d-6de166bc8f33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Browser/Open Web Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34e7fa8a-8312-4edd-a444-6739ea8a873b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e1056c-64bb-4d53-804d-58a5624c7a74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46df1235-89f2-4d7b-9e61-0e966fd95905</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60115896-e4e3-4404-addf-e53cf36b0ff7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Call/CS Fallback Outgoing Call (SIM 1 O2-UK TMO-US)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a3a43b-fb76-4a07-823f-2a9d59a98e59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e96e21bc-c2b0-4042-ae76-fb3e134529f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>477dfbe8-5621-4491-bf25-066b892f6433</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e77262ec-fb6a-40b2-9163-7d7940e05d1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Call/CS Fallback Outgoing Call (SIM 2 EE ATT)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1135a26-f839-4604-9b35-2409963fe59f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbeae097-b515-48a4-afda-6d97135f0651</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>903f6970-1984-41aa-bbbc-d1804e263861</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3ff3909-d880-4fde-aded-d41a09e7852c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Call/Launch Phone App</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07faa306-83b5-4702-a67a-a01a5f5ba845</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1de3e94d-b118-4a09-aeca-ee3d638c01c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69b8d63c-e020-4262-8a17-bd0da995279c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22e06a12-69b4-4602-810e-4d1832132afa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Call/Place Call to Favourite (SIM 1 O2-UK TMO-US)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0211134-c250-4e5e-8c2a-cf86d8b11368</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88be87cb-67b8-4d78-b5dd-c5d127050957</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f3bc9a2-1411-4598-a54b-968e28c75d4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72144772-519f-4c8f-abe8-6ff64e65de9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Call/Place Call to Favourite (SIM 2 EE ATT)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0714a69-accb-4c19-bb93-fb5da3c0a494</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32c28604-4135-4c2f-9c70-d808f7ab19c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0654d063-388e-4891-8ecc-a404df4c20b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7096842b-8a7c-4e14-bb88-f0d7e736dee8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Call/Search Contact and Dial (SIM 1 O2-UK TMO-US)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79ed9e1d-fa45-43ba-b10a-d246a27b77ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a0de9f9-c903-40f3-9a0e-ac55f21dce56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>019116b3-af37-45fd-9651-3615c13c5099</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50235929-95e1-4e20-8540-f84d85186094</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Back Button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99a1fce3-564d-4cf2-a164-53e6d45b0428</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30146a99-39a5-4430-aad5-482a4b15c256</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>603dc7d9-ebf9-4ff6-9e98-cbb2d6439ceb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5ba7d31-0798-4c01-a86c-d299be5ca8cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Functionality/Burst shot Mode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab52c715-87fa-4c82-b4e3-08f20247f99f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee4168e-d6cd-4d12-b4ef-7189b31e03ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f816e6ca-74ef-4274-8575-16d84bb65c85</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4387e01-f3a9-486d-abd5-300f2b5b9219</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Functionality/Launch Camera (Lock Screen)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce8ea733-9593-4b67-b30a-38382491213d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d04cb7e-c9e5-4dfb-8276-78536f3fd490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b038da9-d31c-4679-bc9d-b99eead01bab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3b414eb-5e94-4908-9309-3bd180867af6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Functionality/Manage camera when locked</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>282f919a-9d6a-4fa8-927c-6a13d415cc0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3073422b-3531-49cf-9080-e4708961f3c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>561821be-c5b7-49b5-b310-f8ab1502a7bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>027de99f-0747-41bb-a61b-3bc86fa8e254</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Home Button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e7e04cf-a860-42ad-b5c9-f67db2a88b69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b598ca-a3a8-41a8-a353-622fac1c267a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>490767d3-ba4e-4e9e-a6da-0e05e705bbeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ebdbef2-c740-4b31-82e5-e1f0f177e5af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Photo Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6cbe38-f197-4cd0-bc9f-1c81f4e9f777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c033a7eb-a623-4c4a-9cd4-ae0d69425122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>144c385d-4f2b-47ac-b7a2-62d7e7703581</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f97f744-aa80-46d8-8861-907fd343eed0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Camera Video Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24288b5c-1162-420c-a15d-8febe4340de6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5008a46a-c859-4508-afca-0cf157195950</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2719ae3b-de40-45b5-bd71-7c5cc26325fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd065ea4-0b44-428c-b078-bbe66efcc702</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Delete Camera Photo and Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b9c84cf-e7b3-4031-bf55-14566eecaf9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2891d33c-6d3a-423e-9e86-5d903399befa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7673a160-8e4f-4021-9040-ff92aa943221</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72b73dad-1a2a-49be-96b8-84fef25190e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Front Camera Photo Resolution</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff9d34d4-82e0-4b6e-ae34-3053639b6c63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a885c152-b467-4cbb-bfaa-a0bf029874ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0804f44e-6b74-41cf-9f4d-ed9e3a86010e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e5d2eaa-4b9a-4899-a0ac-c26bbcbe49e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Front Camera Video Resolution</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9e08901-e59a-4d58-aff9-b38106eeaed1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a67de596-3d54-490f-bdfa-2697cc4dd21d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f65ecd-b1bf-494d-b911-91e6174c1077</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56a1e6b7-4470-41e4-a1ff-274bc74f297f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Front Camera View and Delete Photos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb95cee8-93f3-47f8-a154-cf162d6c5b71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1698226d-7b14-454a-b124-4b0924eaa382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8350c0c2-d075-4699-9210-49c4212d5e16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>447269af-0b23-4dd6-aae4-dc294bb30f83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Front Camera View and Delete Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d248cbe-abfc-42fd-ab54-580ac6e28736</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82d1ed03-24fe-418a-b9a0-6386218a660d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6c2990b-7142-437f-a641-f7b52918cc61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04919cc1-17c4-4f84-a873-37d2b0f96203</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Front Camera View Photos and Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1fc68e4-a60a-42da-98ac-adb96de520a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9631ca80-2a3a-4fa8-a95c-fc5e1ed4e5c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a35babc-1047-46c1-a7d7-4d359f7dbef5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6925c67e-3051-4af4-be02-c212efeb88e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Front Camera View Photos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34845c12-e0b2-4fdd-a4ed-50db34088d6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41dd5351-925b-4313-8451-8d4e561519ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b103e24e-22e7-48e9-8969-0c0252f84d05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2aaea33-d16d-4e3f-a504-3a1ae1b72abe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Launch Camera</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b537a79-47f7-4d41-8f8a-e9ecf9139766</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd79e233-1195-4d13-a8ad-f819914a860a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e0f99ce-1df5-47a9-8e39-c55b172e0453</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5bd1bc1c-93ef-43b5-a50c-e4eeb0427315</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Rear Camera Photo Resolution</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e84a4bc-d3d5-458f-81dd-463f438ae29c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c444442-3c24-4fff-9b47-0d0970ce90fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e7b55a-4ecf-44d2-af17-47ac8f17237d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>527f61aa-b13a-4df1-aa0b-0bbfec30cf70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Rear Camera Video Resolution</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>963f4e72-fe05-45dc-aa7e-2875974bdefb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00918a36-24ae-4d97-9c8f-e8903daecf43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea3c561-357b-416d-84bc-b6f211cffbdb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3abfaf92-3736-42e9-91b4-e8bde67bc74e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Rear Camera View and Delete Photos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9d8aa00-eefc-4db1-8902-cccf13c425da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da05d320-5edc-49dd-8008-b9668bf3d4bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70d454c9-5b18-4cb9-a573-c5444270c133</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47b03b41-ef6a-49b1-b45f-874872d8d3e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Rear Camera View and Delete Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42db692f-19e1-4e87-90ec-97d7be6f59d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae56ab84-108d-4ba4-a394-ff6f4de237af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf7a6f71-c57f-47c1-8494-b3d966dedf13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2e0c854-fcec-4f59-ad5a-2c0986dc1908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Rear Camera View Photos and Videos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef7e1636-4e41-4348-bbd5-3196ff09c35a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c71a755a-d509-4fd9-a2e5-d3f57e2774f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b32017ea-58f6-4008-99dc-4687621ddc91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a5a70cd-82a1-41fb-8420-bf4ffb4920a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Rear Camera View Photos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fe940d0-0391-4249-8495-61c7322df67a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b50c39b-343a-4962-8187-b1dd9e4f5d83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e615d93-a097-44cd-849d-79d566195a0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07a9612b-e77f-4eff-a782-acd80bb05c65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Switch to Front Camera (Photo Mode)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>960cdc86-6356-462d-bfab-c0ea2e062193</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14af7d93-3999-44f6-9b0c-e2520857bc62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cf39388-31f7-4760-951c-7d0201ceb63b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19243d45-978a-4feb-80de-015e335b9b33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Switch to Front Camera (Video Mode)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdf195da-eb05-48c3-bd27-5d9f04ed1bce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79bf15bd-5a3e-410d-8fba-997f8aca7250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03e2233a-6982-4bff-aa27-220dbd74eaa4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dde5a780-be82-40b1-99f7-d8c1bca740d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Switch to Rear Camera (Photo Mode)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35bfd3c9-d6c2-48b7-97b0-c357416c5e3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ae53745-a0cb-4cf8-85a3-7030765e69b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ca60af-049a-45de-bf91-6c1cf5af1891</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8abfa2f4-c2e3-4731-b67e-0096d0eb3232</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Switch to Rear Camera (Video Mode)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57fdcb67-7902-43d4-a5ad-46f239a680ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11d304d7-5bcc-46ed-add7-47d777d53319</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ff30611-15b9-445a-ae90-560cc407cd3b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62caf86d-d1dd-4fcb-97ba-501a27b9bc50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Take Camera Photo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a9fbbea-105c-4ce3-a237-e1cbbe820f54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72a3f38e-2192-44b4-8481-000d5005659a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bef2b659-af59-4c7a-af49-9a990e96f68c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70cac408-a6b1-4ba7-829f-2a306de95c55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Take Camera Video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f02d66d5-602f-4fdb-8833-ed1f7438232f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4f68fd9-93b0-4396-82a6-44336e39f0be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5916c4a-0108-45b9-bbab-e3ad3788d710</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e625d70-369f-44f1-b795-8e13603a12b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Camera/Verify switching between Camera modes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2128dd13-7ccc-4e9e-abcf-fee52035810c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>639ac4b1-2849-4c9b-9010-b7ef7acb8e71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c3dbf5e-f303-4efb-b397-8bf17157255d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e06d4b2-c705-4b76-8d6d-d72f6a46ed16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Add a Favourite Contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8d06249-c3b6-45ef-935a-4e968b0a78e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>976afabe-1fe9-43d4-a103-52d6e2ca3f9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ecf30da-c9c5-4fe7-8d2f-1954879ce436</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4ae9987-1cc7-4f57-8b49-46d1674419d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Add Phone Contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>911e0526-7ced-438c-a4dd-d39ff997bbde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5e9cda3-08e3-4d31-a4f5-35b85eb9f333</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44972ee2-6936-4845-8d18-daa9b7843fa7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1fdd059-9f75-4e92-898a-ef5561f90769</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Add SIM 1 Contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d000521f-04bd-4356-a201-48d0b4df2ebf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e349b613-0db7-4c45-baf0-3610f572c0bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc702cdc-aea7-4126-a9f4-db78ed934602</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee5bce65-cb6d-4e1c-89f9-64d8dc20a5b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Add SIM 2 Contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8def64f9-fb4b-49fe-acf3-3b546b4d64a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d3c5591-042b-4ad7-8117-fe78edc0016d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0578bd8-f22a-4dd6-b097-87245790ca2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afce08a3-e1e3-48ef-9269-b6270b9a494f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Contact Shared via Bluetooth</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ae55ee-6077-4011-8a7a-9b2c4124bd58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42db3f23-472d-4d78-b59f-0eb3727ae84f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5592b7fc-a9ee-4e60-928b-244fb83ec10f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69c050f0-652b-42fe-bcc7-c1529af436f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Contact Shared via Messages app</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7cfadc8-c987-41cd-9043-bf1e9720553f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c410331-6be3-444f-8c2d-a62096e5990c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acf29b6b-8320-463a-943a-2fca57507c11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef66ae6d-9292-405d-9b9e-c0da128116a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Contact List/Google Account Contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>333675da-c17b-47d6-80ff-0d7282fbd1d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3a1c015-5a4b-4bc3-9646-8a59e12cee5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>243fc959-ef49-4e27-860f-d5573b4d93c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8eee0351-87fc-45f1-a9f2-a388234e6abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Bluetooth Name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53a4d61e-61c6-4a9d-9632-3e557da8f3c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2edb08e3-4bb5-4a55-894c-9ae7d6357105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed1a60f7-f237-49ed-bd24-ea92c90dbae3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7189ac0-570b-4de3-a46e-abbbe01f2bb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Date Lock Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ba234bb-85a8-411f-a92c-aa4621ef7640</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3dc25ef-5146-4af2-8a29-e713b535471b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0d1f710-a19c-40f7-9bac-1122c2c19589</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>567387ce-27be-4643-93e2-c55acfaf04da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Extras Folder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e914a374-7d73-4bd7-bb7e-67ba879bd7de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f389a2f5-c908-4eae-b455-c44c27fd335b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bfdb9d0-10d2-48ac-a5f8-f96a2305680a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ff43000-b5d4-4b12-9a0d-eeb5173698da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Add icon to Home screen - Disable</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34bb9e51-9835-4248-850a-d6266245aa96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6329ad92-e012-4a78-aaca-7f1ae0d7c483</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12ce3dfd-5ba8-445e-8ba4-15c397ada8b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c96a27f5-7d13-4ff7-8c7d-c474021dce9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Add icon to Home screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db767cf3-c823-4f11-bb3a-72990c4660bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a13517f-a046-40b4-b526-8b875a1a4f39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59194bd4-e1cb-49f9-98b3-91761196c343</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4f72b94b-4669-401b-bee3-58cdf9d31949</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Drawer Settings - Icon labels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1242d24-5ec6-49e9-8e66-d2ecb3184494</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed939d1b-2cea-4d7a-85cc-1fe2db941051</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39696b52-e7b3-4708-a093-2c12c9ad7ecc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>252a367b-21e9-47e2-984f-ece56c54f9c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Google Search Assistant screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49df81e8-c9e7-4598-a0c4-4134dba0d208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e6336da-3162-43ea-82eb-07aca8793cae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54d5176e-6443-4b1c-ba35-907129dfe99c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d69d9f6-a598-474d-bb7a-7bf1a3da1117</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Home app - Launch Pad</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07828f71-db34-4974-a05a-a482ba219d7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>183343b8-fc52-427b-9287-065127565e40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf00500c-d652-43d8-974a-925fe154f5ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fd4e8fc-03fc-4204-b3cf-04c6924fe95f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Home screen - Icon labels</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7c65ec7-3724-4449-a61d-0ba16e400236</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c5da0cb-f2df-4f34-842f-0566ebaffdc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d537ddb-a339-45b7-b210-ba8e71b13b22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1331b3a-8560-4eeb-a63f-e62f7b42a8da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Home screen/Search bar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d30c84f-8347-4688-89fc-10c33c4888cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa50b3e2-32b1-4a72-8900-948ecb26edd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a46651a3-acb4-4eb1-a201-8ca70d572a10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f6e7dcd-d089-4491-a3e3-a0ddbe4ef052</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Shortcut in the lockscreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17f83ef4-c428-4f39-8daf-639a87a48569</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31ce4b08-ddd3-4582-b267-072abd68297c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>753e58e3-0e0e-4ae5-abdd-535c24e0bcf9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9eb6885-b5ce-4945-bf5b-f5c8ec267212</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/SIM SPN instead of CARD1-CARD2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9d585a2-b5b1-4cef-b948-34b642145995</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3761364f-fa15-4763-9cef-02d338affef2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76611919-8096-4bed-b29a-06806242e5c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>224619e3-a6fe-4f68-b6bc-479fdc2ee3e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Wi-Fi Direct Name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13300e6f-1084-4a77-82d8-96f17fc051c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a55d658-a0ae-4ac6-b73a-eea1a3e3b574</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1c4f279-c9b5-4b88-a5dc-de06bbcd2e04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdb259cd-7b94-4c9f-9c90-308b6ba48b10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Customisation/Wi-Fi Hotspot Name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2beb696-a82b-4c5b-b3ca-26ea868af9bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>762ccafe-aa26-4f67-bc57-1441e2cbc198</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33a4ba20-b566-4a49-838d-594f4fb1bdab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e10397f-d51f-42ef-8e58-5e0280d9415f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/E-Mail/Launch Gmail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e233b960-5017-4705-8af9-e63467afe6b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a551919-1d57-4d9a-81e3-7bbcae8b42ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32aa9210-6e28-4558-a0aa-919aa09ccf60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3c45a4-204b-4bd0-a778-6deedacafb5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b2652f3-391f-48e7-a888-5ec03e8bdfe8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/Bluetooth picture-video can be displayed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ddf2f3-086c-4db4-bc4f-0c13078a9c34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ff9b154-94bc-47d7-82da-a55f844de5db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c49fdf7-4d7c-492c-b6d6-d38f77a1c800</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bafa3ca-fa03-4a67-ba03-309bcbd990ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/Camera SLR Mode Edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>866c0f82-fc13-4107-bf90-1a9a4ad08d65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05f9cafa-4f3e-4c3f-a62e-dc12218bb20c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80c7df87-a3ea-40aa-ae34-edb05b49575d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76c04f36-2da3-4f1f-bee0-608d9e78a389</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/Delete Files</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>989da0fa-8de0-4602-85d9-512b3fce76f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8578c770-5335-4a98-9da5-d79ab39b2411</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93157519-0589-45f3-aaac-cef7ab49edf3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f57b1fa-2eca-44a7-844f-0d4b7830b562</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/Gallery Share</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13e598b9-879b-4fa9-8b27-62210a4961ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7f2103e-9fa7-4a10-8509-6ea3bfea69dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3967251f-a263-4250-83b2-7ce803059545</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b06aa94-dacb-4d80-85d4-4a7d061843d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/View Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>479c41b4-973f-4af7-8ef5-624ad50455bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7760afff-8098-4b06-aa13-e1d37af6182c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2e2c9d-cb8e-4bac-b18d-403650cd66a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>512fb309-22d3-4a8e-928c-93727558caa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/View Images</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fab8afd7-e17a-4401-8e78-928c041c203a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ac327de-9913-425c-8358-ea45ebac11c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62ddf060-c29f-4de6-b045-e18359d5b1b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>312ff085-6edd-4f8a-80cb-e05c541de157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Gallery/View Videos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1000dadb-6f86-4bd3-90ec-0b5131d11593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2309c806-797c-4c94-9052-048170b36151</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd78fe05-fb32-4628-941d-0560738cb289</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ef310b0-1d16-41ca-bf8b-77c2425fc901</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Languages and Translations/Keypad Characters</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4efc52cb-21d8-47bd-99a5-44ad690326f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3f6cc5f-3e46-4b6f-8a2b-101421311b61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>931478a6-a0b2-4688-9258-fdf5583cbea4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
