<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Network to Security</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>d39fe5ed-9ed4-4b15-846e-1caf80c26c3f</testSuiteGuid>
   <testCaseLink>
      <guid>efb75694-062a-42cc-81f4-e445049691ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Aeroplane Mode/Aeroplane Mode Off</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83654d38-970e-4d16-a9c3-b87f1455983f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22d3b74f-8121-4827-b977-7faff0ecfa58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>315b6342-09e9-4a75-926c-f63774ed4b09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>159ca1fc-9176-466b-886a-1afe9c380e84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Aeroplane Mode/Aeroplane Mode On</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b72bf237-e6b1-4f3b-92cc-1188bf3b2e66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00232717-db32-4e7b-bf07-9319c0e3ec43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b1aa95a-3f8f-4448-b5c9-336583169225</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d64e4b6-5e8c-418d-bc55-d072b8bb63b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Hotspot and Tethering/Wi-Fi hotspot tethering function</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7139dff4-1fd2-423e-b9b6-59f554614064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f672fcb3-671d-433e-bce9-098e8e33ceb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16dbeb07-64e9-44b2-a8f3-5c7e2b197f4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>872394b6-1a0a-4a7e-b67a-3e2b8e407e9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Mobile Data Connection (Both SIM - SIM 1 - O2-UK)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10003800-b55e-4aa1-870d-06b57ae25ff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcef47fd-1677-44b5-be57-9f14bd3877f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b24ab7b5-ef59-481e-85f3-94a4c715ab6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b29e797f-0d1c-4244-95ba-bc58109f5d4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Mobile Data Enable-Disable from Quick Settings (Both SIM - SIM 1)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>521a82c9-1d2d-4d03-acc1-676529acfd8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bffe43e2-0ee8-4a67-91f6-8a950ac8ced4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b511a7b-374f-49ac-a70f-7a028fb51a55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74537500-5d2d-40bb-bb37-f5a8fd6cd85c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Mobile Data Long Press from Quick Settings (Both SIM - SIM 1)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef16f2a2-9ad2-43bc-91d1-7b6b5a8aab5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6b9b1a9-1a74-4249-960e-35646c959af6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>672f4b99-5349-4d22-95d2-1fd39a0bc7d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a790c642-10d1-4158-8975-ac3ae7166092</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Mobile Data Toggle (Both SIM)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0979cc7d-e840-4e86-b8ca-116db7e6cd52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b379a350-6d6a-4014-83c2-9bf27d66073c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c850092-5e9c-494d-a944-18a9bba3c9d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38bdf42f-7f79-4afe-bbb3-e2336dd309f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/PLMN Search (Both SIM)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8de6e47-514e-4824-95e1-6d1076894dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd9ec583-7314-4089-8a82-666962022223</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb407085-d8fd-4946-a422-40022920055d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50cf4b79-4632-4225-a8bc-5a0725d5238d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Preferred Network Type (Both SIM)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b13b42-08ca-4840-8b23-c8f0aee3f6b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>229816c4-bb66-412b-8697-e1df18f0b74d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c968663-0841-4cf3-8ad9-c6cfd98d5b4d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d492bf1f-58a0-4277-86f9-da91110fb5f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Preferred SIM for Mobile Data (SIM 1 - O2-UK)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca1799c3-d069-45e9-a4e8-2e9fc39fdc5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24437fae-3d09-4899-b5b2-45b8eb314afc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c24b78-e39d-4128-abef-2844f1cb0011</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07dd3ee2-c428-452b-beb2-4f8b6f5f7fbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Preferred SIM for Mobile Data (SIM 2 - EE)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>802a12ea-f42b-4723-9af2-23e56af0dd51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1615e0b-339c-4fd2-8968-ea55a5dc2a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0f15482-2ebc-42ac-b2bd-1721c3f8459c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fb8e8ac-8ff6-4f29-aba8-0d4faf35b6f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/SPN (Both SIMs)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e6b3fd6-89c8-45d7-b7c5-654a908d95a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af63700a-f5da-4c14-88cb-195e076995c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4410d653-2c4d-4b07-ad16-60bb12c34ad2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>828592bf-28bc-4cf6-b303-d83014c6b779</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Mobile Network/Wi-Fi to Mobile Data (Both SIM)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c3b9796-af71-45d5-9cf2-6e4e2a9ed7bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b74c573-691e-40a4-9d2c-0213f51a8ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49c1d5a0-a655-4d74-b45a-5d8b071d6688</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9ab9ef0-7c72-4d6f-b76e-0afd14d4f9fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/PLMN Search/PLMN EE</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6b2b63e-4365-4dcf-a2f8-ae4b694d5cae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86886806-c1cd-48bc-9182-8ebaa03937f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f82e287a-e73f-4543-a076-b0aabd5e4841</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f845f450-35a6-4b53-916b-0e3a8ac4c70a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/PLMN Search/PLMN O2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eff48245-4d21-4fef-86d3-8d33515f24ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22e43922-d1df-4484-9fc5-cd20e1c49717</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67c3dfc2-289e-4853-9358-34944e0316da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e42d122-f6a2-48fb-a482-1df81de74035</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Mobile Data to Wi-Fi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d5950ce-5bfd-43fd-abcd-77aca811513b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4c76696-587e-4128-b963-7b17e64dfade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef004bfa-8c3c-4890-9b9d-4ac2a458cffc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b72cb79b-2120-4de0-95d0-44a3936d2a0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Reset OOB - Wi-Fi Hotspot name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6fa245-1c92-41c5-93e5-ffa88a2215a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eeaae5ba-58b4-47f7-acf6-356d3887ba3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a94cb95-eca2-48d4-b164-b57cc7e1494a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6e1dbd0-4a59-45e1-be86-8bb576005907</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Wi-Fi Connection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dbff4d3-02c9-465c-a9c6-45cae819eca1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29cf1907-1780-4ac8-8e6b-188aa8c2b6ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d43183e-4354-43e1-a8d0-02beb6a8d8e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6155743-e70b-4054-814b-240ccdeb2205</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Wi-Fi Direct - MANUAL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78c90bbc-b407-425d-ac64-014d72cb1e3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59f096d5-51d8-4ef3-83bc-b23a40e04cd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>356b79e5-57d9-4144-993d-ccef5660f214</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43a69e2c-c1ac-4e8f-bd12-c44baac8746e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Wi-Fi Enable-Disable from Quick Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c33d5e7b-93b6-49e4-a174-9def105b2a39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a619341d-5b23-45b6-ad72-b93ee15230ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6681d50-0e16-4fa0-b6d8-6f8d35dabd6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa5ae83b-151d-446d-aec8-bae6ca5cc17e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Wi-Fi List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90388664-eaa6-44d7-aed2-dcadd21ffdb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde60cf0-4b3e-4f38-ae05-4fdf7d0845e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51ac3c52-2ef6-4997-ad43-5f5c12c84c4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>499ac49f-3339-4854-8957-f4f640b573a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Wi-Fi Long Press from Quick Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fe1da85-c7f1-4667-ad27-6b78f647253f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9609136c-1c1e-4576-8309-50e93153802b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>422700f3-d3c7-455a-b97a-b6b347268b29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64dfe7b9-0022-4a09-87b2-dabbb5f64ec3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Network/Wi-Fi/Wi-Fi Toggle</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>442dd19e-0cf7-46d3-a4cc-6b411af53ab6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bbfd3cf-1033-42d8-b98b-ac0eca6b8ecb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c12324b-5294-4b59-bd5d-120365659a34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05521ab2-2343-4df3-bb06-63cfd455c2ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Automatic Lock - 1 minute</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43591e38-afc3-4101-9b12-9e3a8a8c1013</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5885ffd2-b6fb-4e71-8820-996b8b16fdde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f451a760-5ebf-4799-bf5a-d7d38caf9155</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f771f175-4ce6-4b51-b2d9-30ba31ae6419</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Automatic Lock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d013ef96-cb07-4cfa-9e07-25ac86f943f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b81f15f6-1e16-4fa5-a88c-1c1cac148129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cd10367-9d10-453c-9870-1a3cd5c2d55f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2fb8849b-14eb-4103-97e7-46947dd61537</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Lockscreen Emergency Dialler</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34fb3253-8b1f-4cb5-9ace-944e44333692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b358223f-4716-4a94-a05a-1a7364fc956f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b1afcf9-7acc-4e22-ad27-2b2788b4c8d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59abf89e-d998-44b7-ad26-e5fa2d041667</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Slide In Locked Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54907f5a-27e3-43e2-82dd-580f1a6f0ca6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a987de6-abcc-47fd-8725-f43ca2739727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e927a811-374a-403c-876b-13813bc88231</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3e3a058-5205-4956-aa3e-33ada49aa432</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Status Bar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2406329d-b92b-45d2-bc08-3d7969823bbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e1e8a44-4e28-4086-9451-14e19dca3e5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d9989be-8864-4355-884d-c3d97d0b6618</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5cbfa47-7838-4e76-a4b6-60bc9a194394</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Verify negative testing PIN on Lock Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfb74496-092f-4d4c-9034-c5bc206bc18b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc5e8521-4b1c-4039-b39a-7ed4567a8ad6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a87e21e-8a58-48ca-9907-c679f9927522</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2c19cf5-2c15-472b-b1d3-98164e81a5b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Verify None screen lock from Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aea43d23-0c24-424f-a733-0bbcff0da67c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3960d85-01e4-44b5-9b54-8091f6ae5d19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dfdba73-461b-4352-a3cb-3b3db4a2bb6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7626c17-cd0a-4994-999e-80922354f035</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Verify PIN screen lock from Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1107c55-0c02-4822-9b89-68c0eaea6a61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a67eaf60-e88a-4f75-bbed-a06f65fad73c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f46a3e4-8c7f-477f-863b-e4e4472e994b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ea59629-4c9e-4d2e-8f9e-b9183f6c2266</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Verify prompt message on Screen lock from Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adb8fb3b-57c9-44f8-8566-5251871b6e2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff923d2a-4726-4a59-bdc6-957d1a21315e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54567d01-02dd-4b62-a9a6-5abcf255ce7f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ab24537-5857-4dd3-8de3-458b8b282104</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Lock Screen/Verify Screen Lock Swipe From Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d492343f-668b-4851-ae7c-122b1d747c73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81219218-5450-4496-a218-7dddaf9d0fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad3350ab-2dfa-4a85-a009-20cbaef5e006</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88a0e37f-4248-4f0b-b65c-0acc7c2de539</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Password/Verify Password screen lock from Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd15bcb-668e-43b7-9d40-6be8f49e901c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e8edff6-9dcf-410b-86fd-72789e205dce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b273117d-d72c-4a19-a7cc-15b750c9ad65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82943405-a53e-4793-b955-bc3aa82fc9ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/Security/Smart Lock/View Smart Lock options</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e32cbf7-c80e-417b-8293-f121d395f65b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eda83a76-9e8d-4e01-b045-2b303a444497</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f44410-0a0e-4696-9932-14c7c9f8e2c7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
