<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Settings Network to Widgets</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>b5c887c1-8d8e-43f7-8feb-ecd07ce4ef45</testSuiteGuid>
   <testCaseLink>
      <guid>fa4f9382-4762-4013-8f27-55ecbca483f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Aeroplane Mode</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a65d6f7-2aab-4cda-afaf-9294dc68d420</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47b77f09-cd2f-40d3-840a-808c892b0e48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>634eea75-a828-4986-a3e7-481ce9b1c2ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a50cfd10-0b53-4a87-818e-21c908cafd4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Data Usage/Enable - Disable Data Saver</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d316de0a-fd7e-41b6-a4b4-97873a22414f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34361f32-d8c8-4bf8-a378-dffb213c4c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e2fff5a-3b2d-428b-a55b-3a9d3443c946</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e48a2e0-6175-4f84-aa1f-f63a8a4f2d33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Data Usage/View Data Usage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>babab873-c242-4959-a07e-a9fa28fa6ecb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88524cd3-ab89-43ee-b04a-ae90e597d7d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a96b84e-f063-4d8d-845b-58e0c4c129bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a51e26e-a8e2-45dc-a43e-964558bef35e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Hotspot And Tethering/Bluetooth Tethering</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c802030-7097-417c-b5e2-df2406af0bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c43d1a4-7c3a-465b-b204-229b9a687279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6879b5-e668-4524-9252-76f5e9136be4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d10eb70f-3b91-4eeb-8803-968ee3cb1d6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a15ab69-6da3-456d-92fa-ba18bb99613e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd2ec99f-db3e-4265-9e81-76d75a3a0a00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Hotspot And Tethering/Turn Off Hotspot Automatically</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adbfdfb3-146d-475a-9d23-5f3b8db182a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22fbf2bb-778d-4de3-8b56-3f763f6954c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1a5bb76-6138-49d8-a736-8ef9797b5b37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5235515-ca1c-4f9d-b166-d84f47a74dff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Hotspot And Tethering/Wi-Fi Hotspot Settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>734a5cc6-d70a-4653-be00-b1587a53fd74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26ffdc3-5530-4750-836e-426fa942840c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e545b44-868a-4874-b691-62349fd25965</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d462e85-3ff2-40e5-aa8c-427aa5160d23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Mobile Network/Add and Reset APN</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90e9d4e1-31d3-44e5-9d61-34a7af0a2e0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68ba1357-f45a-4862-a902-a89dbbcb73b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c2bf2f9-e25f-4988-b57d-a10f48b3ceb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0734304c-7229-43da-b757-6187bd5f4d87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Mobile Network/APNs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69571742-4d0a-4714-b2df-0af1d6ccef7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dd2562d-63fc-49ae-9305-cf8e93133be3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2dac0ec-0bcf-47fa-9252-a0be93b4f8ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ba787b7-5911-4c1c-ada3-39e8b0599206</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d00a7dee-dccb-4510-a46e-ef23da301325</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b264ee43-6ed4-4a98-acb2-0077965c398f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f4e3f28-419d-47eb-a690-3ed023979d39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56d536cd-721a-4f46-ac4d-b57ba6872e38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f4b18d3-409d-4c59-924f-aba408011d6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00b32e31-faab-4a74-bbd4-3d66cadcfa36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f686221f-299a-48b8-acbe-8a28ed5252c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42b1f8ac-5d53-498e-8e51-cc5b46f30ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57e6629d-d64d-4c37-a9a3-0676b3d65f5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3832a32d-ac1b-419e-ad02-ded0f8524327</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaa46b48-6af0-403e-95c6-3b02993107e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04abdb07-2030-4a3d-8520-ae3ba0c62233</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d78d12fe-b0a1-4465-9612-0b59dca66f1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d15ccc89-ab3a-4582-93a6-a918f08ca843</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59d055d5-3b0a-4164-882a-663b31a6a5e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba3a2f0-d838-41d2-9235-f92fcea6d45e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46fabe7a-5f67-4131-8feb-3eef96ec5a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9ad1462-ae6e-4edd-85a7-5c4e3a206984</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1c7698d-c96e-4daf-83d9-1321851f906b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ef78373-f79b-4c87-b533-1e47b19c5ac6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Mobile Network/View App data usage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a4e985c-a976-4c99-9da4-7f903804ec1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19deed42-7f0d-4e89-a1b5-500ac386c1d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4750396b-bb90-4db5-8d0b-b322bbd1b4e1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32704fc6-8578-4933-aaa0-a2d63f320b45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Mobile Network/View Mobile Network</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18df87b-4e21-4afd-b32d-a653ce582386</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcaa704e-3db3-479a-bf27-56bcb3c89223</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a26f6d76-9745-4267-b53b-66170f3ba506</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40cb0099-6daf-42cb-ad42-4fd3684f96f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Private DNS</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1f89b42-ffef-465e-a84e-de778ac6ee31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7d01034-1752-4598-8091-976782587de8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed44ce79-6c11-4930-8105-ee994e370511</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6346ea5-6561-4375-a2a1-10db0375bd09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/SIM Cards/Update Preferred SIM for</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98508231-23aa-4ab1-9abb-0afe4336a8f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33fa0c65-8be0-4ff3-8efb-e91da185dd46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af0f99a5-afe5-4608-bd85-7486410f8bb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf278ab7-5e9b-442d-8df8-ee876944a3d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/SIM Cards/View SIM Cards</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c563d785-72b6-4c56-90ee-40f41441810e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a4aa893-b539-4c05-a8e5-d59377738c77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd5f0233-6c05-4a54-86a1-0b6f3c33d949</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e4065ef-6d67-4b58-95b7-b58d2e49d01e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/Forget Network</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7fe654e-85d0-4f8d-befa-54545b4df9a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c42321b-2cc5-4dc0-9ac3-cf41e376ab25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f94b3ad-8eb5-403f-86ab-b191e77969e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b48b7953-5a3b-4797-9cbf-01388ffd8189</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/Incorrect Password Wi-Fi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee962b4d-6dbc-49ce-b634-000b318476b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94931a8-8c45-4303-b1a6-692b594537eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>408ac1ce-3bf5-4095-8d09-cfaaacb82fc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41290ddb-68cb-4384-9c85-4363557c32d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/View Network Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0827ac9-a05f-40d6-b243-8c61a43254ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5930f83a-0dec-43d1-8b89-7cf95dc8f370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69a2a6eb-a17c-42b6-86d1-5766fc155771</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a368f1c-ee5c-4f53-8dc6-8b13c68a3716</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/View Wi-Fi Direct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>effa97f6-9137-4699-8a8f-fb0da9fa1a58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccab2dc7-e774-411b-aa64-d32c7a66215a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3358ec5-4eb4-4d45-8bec-8833f9e78015</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb8ccea4-40a1-4039-97ee-cf46506b72ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Network and Internet/Wi-Fi/Wi-Fi Preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d5c99a7-02da-4b64-b5fb-21e3421c1115</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba38ced3-c9f1-4192-b310-dc0666567091</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a580d70-5c08-4ca7-8129-92783e61a784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eef841b4-5512-49aa-8fd6-a66965349417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Device admin apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e89fc6-64d3-4012-9d96-fd93aba739b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d9d771-bec7-484d-9bd3-b012b9f4ae72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12e4c408-6e60-4c34-a028-177ccacc494f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffbb3cb5-19d5-41e7-b0a9-b2128fd10c5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Lock Screen Message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>396073bd-0204-43e4-87f8-e63673f3328d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04e4174e-aadf-467a-930c-b2726ce062e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62f64b18-229c-48ff-a588-0bdc32c7ebbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a77bd5df-8275-4d52-a196-6415aa4ca04e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Lock Screen Notification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>552ce616-b731-4d13-8423-c77a318b5522</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3006b54f-9363-46ff-b18d-1269a64a80a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e30818f-0be3-4788-aa3f-24e1b8ff87e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45eb16c0-6eab-4659-aa42-f8e22468fe31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Lockdown Option</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f015e9d9-6dc6-4008-b62e-1c00759aa737</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc19b241-50e5-4402-b1af-df3def99fa16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac92c7e9-6dd7-45bc-b729-de0972c49104</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59aba3e2-3abe-48f9-a8a6-be15c26c33fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/Screen pinning</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>450bc980-bc88-4bab-b619-aeaf92eb7ea3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c69a595-a525-45ec-8eb0-47ce5bf045ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dda1387-feaa-44b4-a2e5-08c8efadb2d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a8e9992-41df-4cf1-92fd-9a708feb2021</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Encryption and credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d09624fe-866a-45d1-88c0-65cdfb1b3674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a9aac3e-c571-4db2-a9cf-c6b34a476585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15931ee4-9284-433a-9313-f83d8abddcf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6725839e-7920-4b1f-b9b9-ef2c7bc2bc4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Location</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d564d2c5-112e-4240-ab4e-881096677c32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c79a3a29-519f-4f96-8579-c514d4902e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dbaf6db-3828-45e5-adf9-b55edcaf91ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b276a430-401c-4b81-97a5-cc8239317cd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Screen lock (after setting security)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e58102a-f924-4602-beb1-9332c72ea116</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d903211c-c619-409e-9fdc-5cecdb80f1ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57fe09c9-9dc8-419d-a569-d1dbeb9aefc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>880fbdaa-d49d-4bdd-9465-aac08db960ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Screen lock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5c466e5-82df-4460-be0c-082f9aa057df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ea7ade-584f-4bf5-8a0b-dbf6a82ec01c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5de5b6-0ac1-4d11-a24c-ad6f5409a6b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>588e88b1-4f7d-44a4-94fe-fce26536fe4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Security And Location/View Security status</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2faf00f9-0a2d-490e-9b63-d7bab1ab5777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0099a6d7-6693-46a9-87df-0c77ce5049cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aebb4ea-1e0a-417a-8906-cacf71608c84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e0b6e3c-bce3-455b-adca-053f69b5b2e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Storage/View Storage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941d3b0f-85f9-4fa2-a9f0-408fb5e0a908</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bf1e039-68d6-4ed5-b2ef-0c56defc6ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63921b26-e4e5-49e4-afcc-be2ef1a16b7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa0b156e-41c1-4674-b79c-2897e231636f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/Add Emergency contact</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1495b1e4-594f-4665-a9d2-b1b786128c1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3044bfbb-fcd2-475d-8ad0-4e8ae604a7a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ed34db-efb1-4239-b87b-12a599f0f79d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce25a2f0-d900-4004-94d4-d7033e47f6dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/Change Device name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ccfe6ca-04f4-4af5-92b9-f27fb758be87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80989b6c-799a-4e36-9202-2e93cfb3d36e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1848647e-cf16-4dcc-acdd-f8ac135ea150</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fac8b94f-ff62-44be-a924-746304038e86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/Edit Emergency information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41edf871-681a-431f-a9de-d2ea5c6e9eaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c76d5c25-c7d3-44a3-a597-930ff9d324ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28b70c57-40be-47e9-aa85-f0a67cf760c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3cde73d-fc0c-4a08-8407-b9785f7bca9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View Android Version</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92882168-b018-4e70-8aa9-812a98592114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a10d4fd-2370-402c-a2c6-5936dd309489</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3d78ca-0348-4545-994a-97347f7afec0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b374c4a1-3b48-455d-9a8d-df80581ec259</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View IMEI (Slot 1 and Slot 2)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f0f3dd4-7758-4661-a8da-ed4682525d9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59deb499-9632-44cc-a771-aa15b1e60458</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c418209-5063-45dc-adc2-0b26c1bc1bc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b502bf0d-3b31-4a82-89f6-1d7615303b48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View Legal Information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bedf8621-3285-47be-86b1-a3ef408817f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>498a1f2e-101a-4666-9fd1-8045aef3e6ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7154a983-1649-47bc-861d-11eae44aa99f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a97c50e5-6d2e-4a84-87df-7fda95c8848f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View Serial Number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>559c0366-0957-43f8-833e-6a14a10464d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1040acad-71d6-4c65-a219-ca49d26a30e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1acf59f-93bd-41ca-a7b2-01f77c460f16</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5bb7925-a141-4337-895a-3c1bb015c32b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/About Phone/View SIM Status (SIM 1 and SIM 2)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d208c5f0-6dd7-402c-98c0-73d9e682e669</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85aa50a-e77a-4751-b2b9-94ca6cb15cd1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e869c3f2-1668-43cf-8a85-3ad77224dfef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94815a37-073a-4d14-b4dd-08046697a4e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Backup</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0435c360-2d6a-4e01-a4d1-0fcaed8969b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62a3392b-3c33-4f0a-bb56-56fd3e627334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90288155-cca3-4fb7-afbc-a15fc7ca94ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18067f9b-191d-4ca8-a752-73b71aba65a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Date and time/Adjust Date and time preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>924869a6-1141-415c-8cc2-63ac2c425fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dde99fa6-892b-4d08-831d-128cc1f8fe71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9189699d-2f9a-4e90-89de-39f48116126a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4800878-a999-4b60-8f2d-78b0332b87de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Date and time/Set Date and time</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2ccb60-2b07-4b60-a8f2-c20cafa12362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff813350-8ea4-4db3-b81f-096689f9db05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec8e0e5a-9549-460c-90dc-14af842f0879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56881662-2fd5-453b-868c-d2fb763ebb09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Bug report shortcut</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae3c7982-53e2-41ce-8c3a-0c3d6a20d278</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c08a1a26-ced7-43c2-be4f-b1f7b0031617</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354d0a31-2b01-4f6d-b139-a30d8cf3b56d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e4a2f5d-3de0-4b2e-be13-8bc7e5edd182</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Select mock location app</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac34377d-4ed3-45c5-b1dc-3706b048b1f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a197822-cd59-46d0-9d44-3321abc2b20b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b74ac28f-cec9-4c12-84ab-9bad75287520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9929b5a-5cee-40cb-8328-5a31883a0b34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df958ec8-62f7-4c0d-8710-addd67b94a49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edf6aea3-88ac-4d15-9a53-501ffd134fcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Stay awake</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65270204-9111-4ef2-8146-3f780d58b46d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8818f585-ef13-47c1-9522-a7b11522e5c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86148b07-d301-4dd6-9ee7-325c2af0f5e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47bae482-7414-4f85-a24d-24192a27bdf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/System Tracing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb87ae6f-879f-4d89-acf2-86d74ad7e01c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8474c620-d419-42f5-be37-d699d9504e6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>161c1c6c-94cc-4e7a-bfab-926c53403788</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0d04a1f-b93b-400f-b5c4-e2175da62563</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Developer Options/Take bug report</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>969a9a2a-b699-4288-8ebf-c4724b4a5ac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f72c925-c326-4fbe-b1a5-a5aaa6c97c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2bf8c44-487d-4f17-99a8-f33a43e1256f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78f2bd04-5bb9-49e3-af4b-feddef8f3d98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Add language</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e950ad3-91a3-4c5b-899d-c01b158b8a12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df8a6d46-78ab-4cbb-a936-053ad4f87e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0863518-5057-4046-a3c5-e05befed5b9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>173003ec-d834-4634-a066-3b19e5c99998</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Add keyboard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad0c0e2c-e4a5-4b9b-8f82-8c2916d241ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0b16b9-cda5-45fd-99df-0a73dc6a280b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44d7a2ff-af3e-4f78-920e-1f9f11938b99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6de8518c-1ab0-4073-8453-69b271f9bd42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Advanced</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdee5dee-5187-42bc-af72-97ecece679a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>669ec3ba-b16a-4010-8058-5d90878367d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad3cf948-c926-4012-90fd-c787cdefd61e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6e126a1-830c-4133-94d1-75d6573cb090</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Dictionary Add word</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54d4213c-545f-43ef-abc5-4101bc665b68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30c00757-2408-4ecb-beee-346421ba77d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a97a2513-0a7f-4a2c-a00a-215cdc0cba51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a2e808b-793b-49af-a6aa-a7ee9c7db0e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Gboard Dictionary Delete word</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e6940d-f109-41bd-b352-5f6f35c5039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d0765eb-9a0a-4dc3-af0c-3d61f417b8bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ae04e4c-2f62-4067-8377-e32a76905b00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c7a4a99-8a4e-4346-85d6-dfbe78ff52e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Google Voice typing - Support</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4c71212-a9e5-402e-a6a9-4f1e8d37121e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e86c14-a027-4713-9949-576ad40972a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6832d49-39ae-4986-8aa1-cb926976c043</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c99e7a2a-2936-46ec-9d48-bcfdc70d5231</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Offline speech recognition - Auto-update</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fef8810-c7e5-4d67-a7c6-6da0960fcb11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc3c3290-4064-4b73-af0c-d4dc6978cff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31c03aff-2496-48aa-9ed1-e3f79315384e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>342884fa-8738-4026-b5e3-37bd69d6559a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Offline speech recognition - Install new language</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7808705b-c9df-4b29-8500-35787ce14809</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fe2a3d6-19f0-4ebc-ad53-c9a7baf9e6f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b8fbd3-ca87-4570-8a08-b3f7c529fcb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aec05c9e-64fd-41b1-812f-d67bd583cf35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Gboard/Voice Typing/Offline speech recognition - Installed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dd061d2-19c8-4bbb-bde6-13f902b86362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47a75795-8327-4f26-a360-571d4ec77cd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef85b4d-571c-49d6-ae6b-73b1118f996c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2b7e489-d343-45ec-85d2-96e5aabd0e85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Input Assistance</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acbe2bee-1b39-4795-8d73-9f9778efb6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>692632f4-4a33-4915-a27f-6096b41e752b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64aac18-5963-477d-bd20-06ae1c34e0c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>734bbc6f-38b2-4e04-bbe4-22377c16d2d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Personal dictionary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa6ff3a-7f2b-4752-a4b5-d9142e032bf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7ea5088-fbe3-41b0-a427-a01ad0d089cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e47d96b-f758-4553-b12a-7a61c45b5541</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6516317b-8b5d-48fe-b32f-5e75ed38f799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b25fbd32-b8bd-45df-bbee-f07ec9662eda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aaacebee-6e5c-47a8-9f83-196d42eb729f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Languages and input/Remove language</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35adaea1-e050-45e8-bb10-68a2b02edcd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fab8b66-9795-4fbb-a2ee-7a047c440eaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>415a0110-9fc9-4c29-8b0e-6eb0a63ba558</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3c98b8-1f69-4d68-8296-c242fa3c94b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Multiple Users/Add User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0327072f-91e0-404d-beec-77b73f0e2715</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac49a8b6-6ee7-4708-a205-52ab1ce490a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06f0d9fe-ee42-48a9-bc82-adab402d189f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5780ff86-d73f-4c0f-a01f-47e81bca59d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Multiple Users/Guest User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c2f172e-52f5-4459-8a8d-8229f4e340d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1ab664f-7648-4f0c-9d28-a09e81378f46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f470e3-8bf7-488d-a161-028e1dcbe585</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d6ce48e-3937-459e-8db5-add56c0fa199</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Multiple Users/Remove User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63a79c13-e9e2-4eb6-a1e0-9ea8c3b064b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15ea5262-12bb-4b2d-9202-fcc9577f4e41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c31572c8-876a-426a-a4e4-045c154e1e37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>675ccfe7-4ae3-44e0-b77c-08da3f63748c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/System/Software Update</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58a36522-0a65-4a50-85e3-49ef62d85256</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8745e46a-621d-4cd0-a39c-59be4be89f80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d15c65cc-562d-4cb6-ac5e-532a5f1dbb81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>980568fe-edcf-40a0-8b21-1d9d14175535</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/USB/View USB Preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77310f81-f202-4849-b4f0-77b42cc6a38d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e20c9c93-f1cd-4ffa-a8f9-b247e6a173c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c83c892-228a-4be7-b702-04af25f51f34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fce0687-9af0-4d02-9e51-c86162983f0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Verify Internet Widgets</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5514e609-f28e-4298-80f2-a82d36725742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c93a84f-ecb9-4329-82ad-b8752a67a102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93bedbe-4c3d-45c5-a5f3-1eec0983f7da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8ea3310-9d57-48dd-bdff-3efcd0abee30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Widget - Add Settings component</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10f8d9d1-b387-46c9-965f-33a754a6ff8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42f1cb50-4573-40ba-bb7e-2f74e0a3fd66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3dd74d-938e-4a36-a843-6394d69a02b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d15e8b00-26ae-4bfd-904c-93d71cf5189a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Widgets - Bookmarks</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fc44875-c08d-4454-b5e9-870490b2102b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0489b7fe-ea44-4da4-a843-2055c46b7260</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e412f97a-f823-496c-bfc6-c30ec1d6aa6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4979c10c-5d45-4049-b928-b9bfecec1f1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/IO Pro/Widgets/Widgets - Clock</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b2f7ba8-65c0-44fc-a0a2-1df589979e25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb64d87c-c13d-4d27-878b-a3bdb66e4118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d4302c3-f052-4531-bb76-5dc5b76612a7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
