<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Settings Accounts to Google</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>b67227a9-8421-4bcc-aafb-fda143fac758</testSuiteGuid>
   <testCaseLink>
      <guid>4f6e08c1-85d1-4f0f-9603-f224f982c1db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Accounts/Add Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71808f0-9002-469a-948a-0ea96ca6f9b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ecf96f8-a800-4116-98db-0c79b9fa251a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3057aae3-0e66-4701-bc0b-5ca24584000f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>581965fa-dfb5-4068-babd-bc4d0d60ae4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Accounts/Remove Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>068efb37-75e7-4d60-bb3d-2c0ca70be680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c52c1ea6-4ccc-464e-b667-6d89683990c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>522142f1-9a69-4b8b-a046-ddd59ca8e50c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e41d0b03-5e4d-47d0-866d-b41741e3a10c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Accounts/View Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96352085-1cac-42c2-8561-c18b83194792</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf36c15-adf7-409b-b03d-61a4da04c8b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4082d35b-70c7-4b92-b001-884ce3c03efa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0ac2b65-b8ac-4c98-a125-2f20bedee091</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - App Permissions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79a8b371-382e-4735-905d-f33d5d62834e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e9c6975-81cc-44fe-ba16-503fda6def87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daea9181-0870-48c0-838d-e9e4f3d0dd43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50f78b0c-f06d-4d13-9735-03dcc29d04ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - Default Apps - Opening Links</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>313e4fad-f6ea-4be5-8c63-7a9dbac425ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f7ceae7-6ff2-4fc9-9abd-f8846ab9218d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6afbc758-3cb0-4965-9a79-d453744e5947</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac5427dd-8113-4160-9f5a-9340d3eebcca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - Default Apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c7a2c36-ad57-4f43-80ec-2a0f1013ab58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbe354d5-67aa-4dca-8689-29e379740d31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d3efa08-d6a9-48d9-bfaa-48ae59906808</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>901d258e-8e10-483c-919d-c1c59071bf91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Advanced - Emergency Alerts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7828f40a-9b09-468c-b137-4a0d2be3bc22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f071a5e5-49f4-4ece-b1eb-cfa567a97160</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54604531-3f59-46c6-83f8-3328f8212972</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aca11382-ce43-41d2-8377-26106da7ca5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Disable App View</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1df3356b-7803-431b-9e44-a7a5d43e080b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>376d23d0-208c-4362-8bea-45ee946ca728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>400d5eb0-e055-4316-96ea-8ff6e8217423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf81c583-d8bd-49fa-b3b4-872a2a5517da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Do Not Disturb - Turn On Now/Do Not Disturb - Turn on automatically</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c9cacbe-f652-4b25-9c6d-20f392b51e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aee82769-f6e6-4541-9da5-3e8e5bc668ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9b00855-653b-46cc-b2fd-87eb768bcc38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4efc97ac-5a07-4b69-9358-3a07777e44de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Do Not Disturb - Turn On Now/Do Not Disturb - Turn On Now</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>540a3fe7-a8a3-4894-95bb-e166c0880a4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d536b6f-a8ed-4344-a23e-005363b3f361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b970014-c51c-4f22-b065-c3fdcfd21643</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47377d34-225b-45fa-baac-18eae7985397</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Notifications - On Lock Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f374ea74-2fbd-47f7-9d45-80a354d3643d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f43952ba-25d6-414f-bede-509906d341a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63b911a8-fc12-417c-8b8f-00d3ed154bbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd9bdd5c-20b8-40b9-9414-182ad2c05d2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Notifications - Recently Sent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19a1eaee-cea5-44ae-b3c6-c0fcb72e617b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4ebb166-47e9-4524-bfd3-8be0e7022150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d86eea4-8d21-44c4-874f-ddfe761de129</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0157e2c0-4b2c-4a49-b425-b5bad390dab4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Screen Time - Set Timers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b64a1a4-14f7-4929-a7de-52526b6c055d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0daaa6d6-2154-4ee5-b38e-3bfde3b299f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eac67b0f-4210-499b-bb98-95ba7826bae6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccd7a5bb-286f-4ac2-8592-c87eaf1b9e9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a5be1f0-364e-40a9-a6aa-7c97c05beff1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90ef1698-3369-4e42-b559-928daeca8414</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/See All Apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e85fce34-6f6a-4293-885d-0cad8f753006</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f1512e8-0317-4363-b4fb-c2099cc50b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c33f9fa5-5e5c-4aec-a003-2e07f14ca681</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f9edda0-48d1-45b3-96f6-5926a502d01c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Battery Optimization</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ac5ea51-e25d-4348-a922-e3d67e520ba7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143c2bd2-6db8-4835-8864-718ae370967a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1601456d-927b-4d78-9369-a2622334e732</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c5dfa6f-4d12-4cc6-a707-a2b61ae6bf16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Device admin app</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93ce381a-bb1e-43ae-8e19-f5e401ea996e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffcdbe8e-e378-411a-87b8-ae9b8f99e5dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcc0cc7d-1a3b-4107-9f1b-fe0eccf9d1eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c1131f5-44d2-48ac-9208-44e2b565e314</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Directory access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff14b572-47c3-4f80-be83-ef8535a69cc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d73649-7ee3-4b95-a9d6-536d7ae8f72e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5db77e2-5af9-4591-a485-de7ffbc01a70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f4c24b9-4d95-4f33-b6b0-97a4a173e403</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Display over apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e37499e5-9044-452f-8642-6b7a3cd7a563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcc62f9f-1baf-4afb-bbfe-2c487b70453d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5ef19d8-5808-4b04-be2e-7c80be9a9829</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>747b0dd0-62e2-4ae1-af25-cefa2280a924</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Do Not Disturb access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c871f0f9-24a6-4181-ac94-be833796def3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb92381c-f0dd-4fb2-9e81-4b88764fc627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>264a43a4-ca84-41d7-9716-063f764074ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51543b60-05ed-42cd-b42e-9c3fe46b2774</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Install unknown apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>398b742a-a824-4a70-8069-e75048392e72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae73eda4-b2cc-4a50-b97a-5790c7eb61fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c43affaa-0bcc-496b-ac4b-c8407fcb9be4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29faa68e-d7ee-4a81-8a76-1ce84a53a180</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Modify system settings</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>645e3faf-ba64-4ce1-b215-b5bb0a95c05f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a599ca4-42ff-4aa2-b4a8-78ccf1588381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f3ab96-6a2f-4dc4-96e6-519f9b502096</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d9fc3ca-210b-4eb3-b9dd-2eaea62dcb80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Notification access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1bcde10-f997-484d-8273-b2413bca940f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7108dd08-7a8f-4c3d-8b63-f0ff013b889c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ca1089e-57cf-45c7-8270-4d515efde9fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90914166-1992-44e1-bd1c-f9608b9c44da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Picture-in-picture</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d65e9d1-242d-49b5-b1f6-ca0d4cd0648f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b6a28b9-e0f2-4773-9f84-edf8e3f4571c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30b6c77b-031f-4c3d-a077-6284e5ed7f88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5367709-2a2e-453b-a3dc-0e42e5ffe732</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Premium SMS access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c88c229c-ec60-40c5-8f7a-122057788cf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98bdce63-4e82-4e68-8457-057a73d1aa16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b767a205-7cb9-4e60-b64b-73d38cc4a958</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2246141-552f-4533-97fd-7218b3d204ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Unrestricted data</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03b253db-0336-44e7-a5d0-651b787ffba4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ecc96a2-2d9c-4522-989b-8dd65b9dfacc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>297eff45-1d2f-463e-a362-603230b1666f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3557629d-0a90-4766-ba7d-635ef2079b8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Usage access</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecf085af-506e-411f-a7f2-f0b034df9926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61a7c498-265d-4ff7-ad2e-b1c7c1489cdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa6ae219-84f3-473d-a80d-7a98d3742e5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecbd4b15-a880-4c52-86aa-cbfb88485f29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/VR helper services</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c0b1321-7857-4e0a-8ff0-db986c96c96f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96bcf4e5-f0d8-4184-b214-99d2128f958a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>507c2573-d5ee-4da2-a089-7b777bac55eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ee665e1-84e1-4456-a6d6-e775b704f9f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/Special App Access/Wi-Fi control</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed41c76-77a7-4461-a7fa-d199e9db28c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34324b91-5729-4715-9d88-c91b322d53bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e82d7c1-7399-4c61-af9e-4c6bb4761a97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d8d8e38-1448-49ea-ab20-22b26e950889</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Apps And Notifications/View Recently Opened Apps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b382119-0c57-4f9f-b866-050032028f12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e56cfa5e-5e62-4f1b-847d-027361b53a01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>044ee2cf-6ea2-419d-88d0-66deca9a8dae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1742ff72-23f2-49e3-b12f-70fbdeb83811</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Battery/Settings Adaptive Battery</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1bfa2f9-23a4-4bf3-a30e-d3368a085434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b8892ad-0f67-472e-b305-184454b69683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8d1d16d-5c2f-47e4-9638-e1d079e647be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7441d93d-af61-4765-8c68-43c58fb1f6fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Battery/View Battery Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec4291aa-8d83-4b6e-9787-0634593e0b24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5343da87-348f-46a1-9293-a7b78f9ad1e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcd736c-3a9c-4a2e-86a3-169a0a96c5a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d313275-32b2-4a24-bc89-0ab882de6a13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Digital Wellbeing/Manage Notifications</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21277910-a4f9-4230-a7a9-c252112eca4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed818a93-8055-43c3-9760-8e55b1b66e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d9bec0a-5390-425c-a708-1434104fda25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77db960f-c835-4ad8-b9db-7a3334e8f4cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Digital Wellbeing/Show icon in the app list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>495fccff-a989-4957-9acc-b35e01d371cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba3d0983-18e5-4fcb-b12d-153f9f321ee5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90f8893e-0153-414b-8843-63240e425336</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41c51960-19fa-454a-aa75-66f899e194b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Digital Wellbeing/View Digital Wellbeing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13394281-3a90-40eb-8ac3-cdff863b2e0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa720567-193e-43dd-8cfc-f5b92f9bc387</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a98c610-0508-49b7-91e2-2aab7cedeff8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce39c489-b5a0-4b90-b32d-182feac9e6d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Data management</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95af7b99-13b5-4d29-8249-22f3275c3643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54da181c-1091-4baa-af32-b896cc90cb40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed06ba9-3fae-40d0-ad2d-225c67479fc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a7cf526-22a6-4a82-9660-89548bd6d01d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Google Backup</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78d205fa-6c35-470f-9113-3d357957f6fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63bcc94d-bfdc-4b09-93ba-f746144817de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fda0c00a-e473-4ec8-996f-ec1ff65a3e78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25852a49-56d1-4da0-b642-3d4c69d3951a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/On-device sharing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff26b7-7628-4b45-8d6f-d163abd83705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f515975e-0ba9-49a7-ba46-6e4b849cc213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>343d4b13-e8b7-4f3d-83da-f7de0507b642</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>818df1c1-0db0-4e36-b249-59eea9dbe33b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Restore Contacts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4881718d-cd53-4a7f-a76e-d85fb7f91e03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c16c5803-4e43-4e67-8dcf-bb6f4ef541de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bec99709-a334-4562-9362-6327c4ba1f98</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17f01d80-36af-441b-84a1-1ef0b8578070</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Security</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6a6a165-a7f5-4736-88fa-513b8f2d4d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c8c7d96-90fd-4aef-b12d-0142f5f623e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43fb3669-3468-4aba-af7b-d9e9ced2bdc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>543976b3-5c7e-4536-90f0-ca0a7170e42d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/Service - Ads</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e636efa8-5cd3-4836-a5f5-d5533e6ce088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4caff1-a825-4e46-9351-d31e9ed2e8cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc976877-5a2f-4e2c-8153-597c4d997f49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72933dbc-c9e2-440f-ba78-69a52488750b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/IO Pro/System Settings/Google/View Account Info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07873038-df84-4b78-9d0c-fe5a50ec79c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03ed12b9-c439-4a08-8583-645bc30eb92d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>381ded3b-dbb8-47de-a256-5cc6e53b4122</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
